-- Closure-free two-level type theory (CFTT, Kovacs ICFP 2024): low code.
--
--   Low a       the meta level type of closure free object code of type a
--
-- Quotations [| e |] and splices ~e are shared with Code (see Staged); a
-- quotation is Low when its type is (Low t).  Low code is a first order,
-- strict, monomorphic subset of Haskell:
--
--  * values have value types: the primitive numeric and character types, and
--    data types whose fields are value types (no functions in data);
--  * functions are first order: the arguments are values (no higher order
--    functions), so no closures are ever needed at run time;
--  * let bound values and function arguments are evaluated (call by value);
--  * class methods are only available at known instances where they are
--    primitives (e.g. + on Int), there is no overloading; other global
--    functions are not available, only constructors and local definitions.
--
-- Low code is generated by ordinary (meta level) Haskell code, which can use
-- all of Haskell; it is in the generated code that functions are first order.
-- Spliced into object code, low code runs as ordinary MicroHs code.
-- With reflect, the generated code is available as a first order syntax tree
-- (LowProg), with the type of every binder, for user written code generators
-- (see Staged.Low.C and Staged.Low.JS).
--
-- A type variable in low code stands for a value type: a generator that is
-- polymorphic in a type that is used in low code needs a (LowRep a) constraint,
-- which the compiler solves for every concrete type.
module Staged.Low(
  Low, LowRep,
  LowTy(..), LowDecl(..), LowConDecl(..), LowCon(..), LowLit(..),
  LowTerm(..), LowProg(..),
  reflect, typeOf, arity, resultType, conFieldTypes, baseName, freeVars,
  lowPretty, lowPrettyTerm,
  Gen(..), runGen, gen, genRec, genLet,
  lowInt, lowWord, lowDouble, lowFloat, lowChar, lowString, lowBool,
  ) where
import Prelude
import Data.List(nub, intercalate)
import Staged.Low.Internal

-----------------------------------------------------------------------
-- First order low code, the result of reflect.

-- Variables are named uniquely in a program; every binder carries its type.
data LowTerm
  = LVar String LowTy                        -- a variable, with its type
  | LLit LowLit LowTy
  | LPrim String LowTy                       -- a primitive of the runtime system (e.g. "+" on Int), with its type
  | LForeign String String LowTy             -- a foreign (C) function: Haskell name, C name, type
  | LApp LowTerm [LowTerm]                   -- a saturated call of a variable, primitive, or foreign function
  | LLam [(String, LowTy)] LowTerm           -- a function; only as the right hand side of a let, or the program
  | LLet String LowTy LowTerm LowTerm        -- let x :: t = e in b  (e is evaluated first, unless it is a function)
  | LLetRec [(String, LowTy, LowTerm)] LowTerm   -- recursive functions
  | LCase LowTerm [LowCon] [(LowCon, [(String, LowTy)], LowTerm)] (Maybe LowTerm)
                                             -- scrutinee, all constructors of its type, alternatives, default
  | LCon LowCon LowTy [LowTerm]              -- a saturated constructor application; the type of the value
  | LFail String                             -- a failed pattern match or error

data LowProg = LowProg {
  progType  :: LowTy,                        -- the type of the program
  progFree  :: [(String, LowTy)],            -- the free (object level) variables
  progDecls :: [LowDecl],                    -- the data types used
  progBody  :: LowTerm
  }

-- The type of a term.
typeOf :: LowTerm -> LowTy
typeOf at =
  case at of
    LVar _ t -> t
    LLit _ t -> t
    LPrim _ t -> t
    LForeign _ _ t -> t
    LApp f as -> applyTy (typeOf f) (length as)
    LLam xs b -> mkFun (map snd xs) (typeOf b)
    LLet _ _ _ b -> typeOf b
    LLetRec _ b -> typeOf b
    LCase _ _ ((_, _, b) : _) _ -> typeOf b
    LCase _ _ [] (Just d) -> typeOf d
    LCase _ _ [] Nothing -> TOther "empty case"
    LCon _ t _ -> t
    LFail _ -> TOther "fail"

-- The number of arguments of a function type.
arity :: LowTy -> Int
arity (TFun as _) = length as
arity _ = 0

resultType :: LowTy -> LowTy
resultType = lowFunResult

applyTy :: LowTy -> Int -> LowTy
applyTy t 0 = t
applyTy (TFun as r) n
  | n < length as = TFun (drop n as) r
  | n == length as = r
  | otherwise = applyTy r (n - length as)
applyTy _ _ = TOther "application of a non-function"

mkFun :: [LowTy] -> LowTy -> LowTy
mkFun [] r = r
mkFun as (TFun bs r) = TFun (as ++ bs) r
mkFun as r = TFun as r

-- The field types of a constructor of a data type (with the type arguments substituted).
conFieldTypes :: LowTy -> LowCon -> [LowTy]
conFieldTypes (TData _ args decl) con =
  case [ conDeclFields c | c <- declCons decl, conDeclTag c == conTag con ] of
    fs : _ -> map (substParams args) fs
    [] -> []
conFieldTypes _ _ = []

substParams :: [LowTy] -> LowTy -> LowTy
substParams args t =
  case t of
    TParam i | i < length args -> args !! i
    TFun as r -> TFun (map (substParams args) as) (substParams args r)
    TData n as d -> TData n (map (substParams args) as) d
    _ -> t

-- The name without the module qualifier.
baseName :: String -> String
baseName s =
  case break (== '.') s of
    (m, '.' : r) | not (null m) && all (\ c -> c /= '(' && c /= '[') m && not (null r) -> baseName r
    _ -> s

-- The free variables of a term.
freeVars :: LowTerm -> [(String, LowTy)]
freeVars = nub . go []
  where
    go bound at =
      case at of
        LVar x t | x `elem` bound -> []
                 | otherwise -> [(x, t)]
        LLit _ _ -> []
        LPrim _ _ -> []
        LForeign _ _ _ -> []
        LApp f as -> concatMap (go bound) (f : as)
        LLam xs b -> go (map fst xs ++ bound) b
        LLet x _ e b -> go bound e ++ go (x : bound) b
        LLetRec bs b -> let bound' = [ x | (x, _, _) <- bs ] ++ bound
                        in concatMap (\ (_, _, e) -> go bound' e) bs ++ go bound' b
        LCase s _ alts d -> go bound s ++ concatMap (\ (_, xs, b) -> go (map fst xs ++ bound) b) alts ++ maybe [] (go bound) d
        LCon _ _ as -> concatMap (go bound) as
        LFail _ -> []

-----------------------------------------------------------------------
-- Reflection: read back the HOAS representation as first order terms.

-- A small state monad: the names in use (with a counter), and the free variables.
newtype R a = R (RS -> (a, RS))
data RS = RS [String] [(Int, String, String, LowTy)]

unR :: R a -> RS -> (a, RS)
unR (R f) = f

instance Functor R where
  fmap f (R g) = R $ \ s -> case g s of (a, s') -> (f a, s')
instance Applicative R where
  pure a = R $ \ s -> (a, s)
  R f <*> R a = R $ \ s -> case f s of (g, s') -> case a s' of (b, s'') -> (g b, s'')
instance Monad R where
  R g >>= f = R $ \ s -> case g s of (a, s') -> unR (f a) s'

-- A fresh variable name, based on the name in the source.
fresh :: String -> R String
fresh s = R $ \ (RS used fs) ->
  let base = case takeWhile (/= '$') (dropWhile (== '$') s) of
               "" -> "v"
               b@(c : _) | c >= 'a' && c <= 'z' || c == '_' -> b
                         | otherwise -> "v"
      name = head [ n | n <- base : [ base ++ "_" ++ show i | i <- [1 :: Int ..] ], n `notElem` used ]
  in  (name, RS (name : used) fs)

-- The name of a free (object level) variable.
freeVar :: Int -> String -> LowTy -> R String
freeVar l x t = R $ \ st@(RS _ fs) ->
  case [ n | (l', x', n, _) <- fs, l' == l, x' == x ] of
    n : _ -> (n, st)
    [] -> case unR (fresh x) st of
            (n, RS ns fs') -> (n, RS ns (fs' ++ [(l, x, n, t)]))

-- The level of the variables bound by the read back; the others are free variables.
boundLevel :: Int
boundLevel = -1

readBack :: LowExp -> R LowTerm
readBack ae =
  case ae of
    HVar l x t | l == boundLevel -> return (LVar x t)
               | otherwise -> do { n <- freeVar l x t; return (LVar n t) }
    HLam x t f -> do
      x' <- fresh x
      b <- readBack (f (HVar boundLevel x' t))
      return (LLam [(x', t)] b)
    HApp f as -> LApp <$> readBack f <*> mapM readBack as
    HLet x mt e f -> do
      e' <- readBack e
      let t = maybe (typeOf e') id mt
      x' <- fresh x
      b <- readBack (f (HVar boundLevel x' t))
      return (LLet x' t e' b)
    HLetRec xts f -> do
      xs <- mapM (fresh . fst) xts
      let ts = map snd xts
          (es, b) = f (zipWith (HVar boundLevel) xs ts)
      es' <- mapM readBack es
      b' <- readBack b
      return (LLetRec (zip3 xs ts es') b')
    HCase s cons alts d -> do
      s' <- readBack s
      let st = typeOf s'
          alt (LowAlt con names f) = do
            xs <- mapM fresh names
            let ts = conFieldTypes st con
                ts' = ts ++ replicate (length xs - length ts) (TOther "unknown field type")
            b <- readBack (f (zipWith (HVar boundLevel) xs ts'))
            return (con, zip xs ts', b)
      alts' <- mapM alt alts
      d' <- maybe (return Nothing) (fmap Just . readBack) d
      return (LCase s' cons alts' d')
    HCon c t as -> LCon c (applyTy t (length as)) <$> mapM readBack as    -- the type of the (possibly partial) application
    HLit l t -> return (LLit l t)
    HPrim p t -> return (LPrim p t)
    HForeign h c t -> return (LForeign h c t)
    HFail m -> return (LFail m)

-- Call saturation: afterwards every call (LApp) has as many arguments as the
-- function type has, every constructor application is saturated, and functions
-- (LLam) only occur as the right hand side of lets, or as the whole program.
-- (Section 2.2 of the CFTT paper.)
saturate :: LowTerm -> R LowTerm
saturate at =
  case at of
    LApp f as -> do
      f' <- saturate f
      as' <- mapM saturate as
      satApp f' as'
    LLam xs b -> mergeLam xs <$> saturate b
    LLet x t e b -> do
      e' <- saturate e >>= etaTo t
      LLet x t e' <$> saturate b
    LLetRec bs b -> do
      bs' <- mapM (\ (x, t, e) -> do { e' <- saturate e >>= etaTo t; return (x, t, e') }) bs
      LLetRec bs' <$> saturate b
    LCase s cons alts d -> do
      s' <- saturate s
      alts' <- mapM (\ (c, xs, b) -> do { b' <- saturate b; return (c, xs, b') }) alts
      d' <- maybe (return Nothing) (fmap Just . saturate) d
      return (LCase s' cons alts' d')
    LCon c t as -> do
      as' <- mapM saturate as
      if length as' < conArity c then
        etaCon c t as'
       else
        return (LCon c t as')
    _ -> return at

mergeLam :: [(String, LowTy)] -> LowTerm -> LowTerm
mergeLam xs (LLam ys b) = LLam (xs ++ ys) b
mergeLam xs b = LLam xs b

-- Apply a (saturated) term to (saturated) arguments.
satApp :: LowTerm -> [LowTerm] -> R LowTerm
satApp f [] = return f
satApp f as =
  case f of
    LLam xs b ->
      -- beta: bind the arguments with lets
      let n = min (length xs) (length as)
          binds = zip (take n xs) (take n as)
          rest = drop n xs
          rest' = drop n as
      in  do b' <- if null rest then satApp b rest' else return (LLam rest b)
             return (foldr (\ ((x, t), e) r -> LLet x t e r) b' binds)
    LLet x t e b -> LLet x t e <$> satApp b as
    LLetRec bs b -> LLetRec bs <$> satApp b as
    LCase s cons alts d ->
      -- push the arguments into the alternatives; non-trivial arguments are let bound first
      bindArgs as $ \ vs -> do
        alts' <- mapM (\ (c, xs, b) -> do { b' <- satApp b vs; return (c, xs, b') }) alts
        d' <- maybe (return Nothing) (fmap Just . (`satApp` vs)) d
        return (LCase s cons alts' d')
    LCon c t as' -> saturate (LCon c (applyTy t (length as)) (as' ++ as))
    _ -> do
      let n = arity (typeOf f)
      if length as < n then
        etaApp f as
       else if length as == n || n == 0 then     -- n == 0: the type of f is not known to be a function
        return (LApp f as)
       else
        satApp (LApp f (take n as)) (drop n as)

bindArgs :: [LowTerm] -> ([LowTerm] -> R LowTerm) -> R LowTerm
bindArgs as k = go [] as
  where
    go acc [] = k (reverse acc)
    go acc (a : rest) =
      case a of
        LVar _ _ -> go (a : acc) rest
        LLit _ _ -> go (a : acc) rest
        _ -> do
          x <- fresh "a"
          let t = typeOf a
          b <- go (LVar x t : acc) rest
          return (LLet x t a b)

-- Eta expand a partial application to a function.
etaApp :: LowTerm -> [LowTerm] -> R LowTerm
etaApp f as =
  case applyTy (typeOf f) (length as) of
    TFun ps _ -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      return (LLam xs (LApp f (as ++ map (\ (v, t) -> LVar v t) xs)))
    _ -> return (LApp f as)

-- t is the type of the partial application.
etaCon :: LowCon -> LowTy -> [LowTerm] -> R LowTerm
etaCon c t as =
  case t of
    TFun ps r -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      return (LLam xs (LCon c r (as ++ map (\ (v, t') -> LVar v t') xs)))
    _ -> return (LCon c t as)

-- Make a term of function type a lambda.
etaTo :: LowTy -> LowTerm -> R LowTerm
etaTo t e =
  case (t, e) of
    (TFun _ _, LLam _ _) -> return e
    (TFun ps _, _) -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      b <- satApp e (map (\ (v, t') -> LVar v t') xs)
      return (mergeLam xs b)
    _ -> return e

-- Simplification after call saturation (all names are unique):
--  * a let bound variable is substituted;
--  * unused functions, variables, literals and constructor applications are removed
--    (a function is never evaluated, the others cannot fail);
--  * a function with one (unit) parameter that is called once (a join point
--    of the pattern match compiler) is inlined;
--  * the default alternative of a case that covers all constructors is removed.
simplify :: LowTerm -> LowTerm
simplify at =
  case at of
    LLet x t e b ->
      let e' = simplify e
          b' = simplify b
      in  case e' of
            LVar _ _ -> substVar x e' b'
            _ | countVar x b' == 0 && harmless e' -> b'
            LLam [(_, pt)] body | isUnit pt, countVar x b' == 1, Just b'' <- inlineCall x body b' -> b''
            _ -> LLet x t e' b'
    LLetRec bs b ->
      let bs' = [ (x, t, simplify e) | (x, t, e) <- bs ]
          b' = simplify b
          used = [ x | (x, _, _) <- bs', countVar x b' > 0 || any (\ (y, _, e) -> y /= x && countVar x e > 0) bs' ]
      in  if null used then b' else LLetRec bs' b'
    LApp f as -> LApp (simplify f) (map simplify as)
    LLam xs b -> LLam xs (simplify b)
    LCase s cons alts d ->
      let alts' = [ (c, xs, simplify b) | (c, xs, b) <- alts ]
          complete = all (\ c -> c `elem` [ c' | (c', _, _) <- alts' ]) cons
      in  LCase (simplify s) cons alts' (if complete then Nothing else fmap simplify d)
    LCon c t as -> LCon c t (map simplify as)
    _ -> at
  where
    harmless e =
      case e of
        LLam _ _ -> True
        LVar _ _ -> True
        LLit _ _ -> True
        LCon _ _ as -> all harmless as
        _ -> False
    isUnit (TData "()" _ _) = True
    isUnit _ = False

-- The number of occurrences of a variable.
countVar :: String -> LowTerm -> Int
countVar x at =
  case at of
    LVar y _ -> if x == y then 1 else 0
    LApp f as -> sum (map (countVar x) (f : as))
    LLam _ b -> countVar x b
    LLet _ _ e b -> countVar x e + countVar x b
    LLetRec bs b -> sum [ countVar x e | (_, _, e) <- bs ] + countVar x b
    LCase s _ alts d -> countVar x s + sum [ countVar x b | (_, _, b) <- alts ] + maybe 0 (countVar x) d
    LCon _ _ as -> sum (map (countVar x) as)
    _ -> 0

-- Substitute a term (a variable) for a variable.
substVar :: String -> LowTerm -> LowTerm -> LowTerm
substVar x r = go
  where
    go at =
      case at of
        LVar y _ | x == y -> r
        LApp f as -> LApp (go f) (map go as)
        LLam xs b -> LLam xs (go b)
        LLet y t e b -> LLet y t (go e) (go b)
        LLetRec bs b -> LLetRec [ (y, t, go e) | (y, t, e) <- bs ] (go b)
        LCase s cons alts d -> LCase (go s) cons [ (c, xs, go b) | (c, xs, b) <- alts ] (fmap go d)
        LCon c t as -> LCon c t (map go as)
        _ -> at

-- Replace the (only) call  x arg  by the body of x.
inlineCall :: String -> LowTerm -> LowTerm -> Maybe LowTerm
inlineCall x body = go
  where
    go at =
      case at of
        LApp (LVar y _) [_] | x == y -> Just body
        LVar y _ | x == y -> Nothing
        LApp f as -> LApp <$> go f <*> mapM go as
        LLam xs b -> LLam xs <$> go b
        LLet y t e b -> LLet y t <$> go e <*> go b
        LLetRec bs b -> LLetRec <$> mapM (\ (y, t, e) -> (,,) y t <$> go e) bs <*> go b
        LCase s cons alts d -> LCase <$> go s <*> pure cons <*> mapM (\ (c, xs, b) -> (,,) c xs <$> go b) alts <*> maybe (pure Nothing) (fmap Just . go) d
        LCon c t as -> LCon c t <$> mapM go as
        _ -> Just at

-- The declarations of the data types used in a term (and in the types).
collectDecls :: LowTerm -> [LowDecl]
collectDecls t0 = reverse (go [] t0)
  where
    go acc at =
      case at of
        LVar _ t -> ty acc t
        LLit _ t -> ty acc t
        LPrim _ t -> ty acc t
        LForeign _ _ t -> ty acc t
        LApp f as -> foldl go (go acc f) as
        LLam xs b -> go (foldl ty acc (map snd xs)) b
        LLet _ t e b -> go (go (ty acc t) e) b
        LLetRec bs b -> go (foldl (\ a (_, t, e) -> go (ty a t) e) acc bs) b
        LCase s _ alts d -> let acc1 = go acc s
                                acc2 = foldl (\ a (_, xs, b) -> go (foldl ty a (map snd xs)) b) acc1 alts
                            in maybe acc2 (go acc2) d
        LCon _ t as -> foldl go (ty acc t) as
        LFail _ -> acc
    ty acc t =
      case t of
        TFun as r -> foldl ty (ty acc r) as
        TData n as d | n `elem` map declName acc -> foldl ty acc as
                     | otherwise -> foldl ty (foldl ty (d : acc) (concatMap conDeclFields (declCons d))) as
        _ -> acc

-- Reflect low code into a first order program.
reflect :: forall a . Low a -> LowProg
reflect l =
  let act = do
        b <- readBack (fromLow l)
        b' <- saturate b >>= etaTo (typeOf b)
        return (simplify b')
      (body, RS _ fs) = unR act (RS [] [])
  in  LowProg { progType = typeOf body
              , progFree = [ (n, t) | (_, _, n, t) <- fs ]
              , progDecls = collectDecls body
              , progBody = body }

-----------------------------------------------------------------------
-- Pretty printing

lowPretty :: LowProg -> String
lowPretty p =
  unlines $
    [ "-- type: " ++ show (progType p) ] ++
    [ "-- free: " ++ x ++ " :: " ++ show t | (x, t) <- progFree p ] ++
    [ "-- " ++ show d | d <- progDecls p ] ++
    [ lowPrettyTerm (progBody p) ]

lowPrettyTerm :: LowTerm -> String
lowPrettyTerm = ppT 0 0

-- precedence: 0 top, 10 argument
ppT :: Int -> Int -> LowTerm -> String
ppT ind p at =
  case at of
    LVar x _ -> x
    LLit l _ -> ppLit l
    LPrim s _ -> s
    LForeign _ c _ -> "ffi:" ++ c
    LApp (LPrim op _) [a, b] | Just o <- infixOp op -> par (p > 5) $ ppT ind 6 a ++ " " ++ o ++ " " ++ ppT ind 6 b
    LApp f as -> par (p > 9) $ unwords (ppT ind 10 f : map (ppT ind 10) as)
    LLam xs b -> par (p > 0) $ "\\ " ++ unwords [ "(" ++ x ++ " :: " ++ show t ++ ")" | (x, t) <- xs ] ++ " ->" ++ nl (ind + 2) ++ ppT (ind + 2) 0 b
    LLet x t e b -> par (p > 0) $ "let " ++ x ++ " :: " ++ show t ++ " = " ++ ppT (ind + 4) 0 e ++ nl ind ++ "in " ++ ppT (ind + 3) 0 b
    LLetRec bs b -> par (p > 0) $ "letrec" ++ concat [ nl (ind + 2) ++ x ++ " :: " ++ show t ++ " = " ++ ppT (ind + 4) 0 e | (x, t, e) <- bs ] ++ nl ind ++ "in " ++ ppT (ind + 3) 0 b
    LCase s _ alts d -> par (p > 0) $ "case " ++ ppT ind 0 s ++ " of" ++
                        concat [ nl (ind + 2) ++ ppPat (baseName (conName c)) (map fst xs) ++ " -> " ++ ppT (ind + 4) 0 b | (c, xs, b) <- alts ] ++
                        maybe "" (\ e -> nl (ind + 2) ++ "_ -> " ++ ppT (ind + 4) 0 e) d
    LCon c _ as | isTupleName (baseName (conName c)) -> "(" ++ intercalate ", " (map (ppT ind 0) as) ++ ")"
    LCon c _ [a, b] | baseName (conName c) == ":" -> par (p > 4) $ ppT ind 5 a ++ " : " ++ ppT ind 4 b
    LCon c _ [] -> baseName (conName c)
    LCon c _ as -> par (p > 9) $ unwords (baseName (conName c) : map (ppT ind 10) as)
    LFail m -> par (p > 9) $ "fail " ++ show m
  where
    par True s = "(" ++ s ++ ")"
    par False s = s
    nl n = "\n" ++ replicate n ' '

-- Primitive operators are shown infix (without the type prefix, e.g. d* for Double).
infixOp :: String -> Maybe String
infixOp op =
  case op of
    c : r | c `elem` "duf", isOp r -> Just r
    _ | isOp op -> Just op
    "quot" -> Just "`quot`"
    "rem" -> Just "`rem`"
    _ -> Nothing
  where isOp o = not (null o) && all (`elem` "+-*/<>=&|^") o

isTupleName :: String -> Bool
isTupleName n = not (null n) && all (== ',') n

ppPat :: String -> [String] -> String
ppPat c xs | isTupleName c = "(" ++ intercalate ", " xs ++ ")"
           | c == ":", [a, b] <- xs = a ++ " : " ++ b
           | otherwise = unwords (c : xs)

ppLit :: LowLit -> String
ppLit l =
  case l of
    LitInt i -> show i
    LitInt64 i -> show i
    LitDouble d -> show d
    LitFloat f -> show f
    LitChar c -> show c
    LitString s -> show s

-----------------------------------------------------------------------
-- The code generation monad (let insertion), as in Staged, for low code.

newtype Gen a = Gen (forall r . (a -> Low r) -> Low r)

unGen :: forall a r . Gen a -> (a -> Low r) -> Low r
unGen (Gen f) = f

instance Functor Gen where
  fmap f (Gen g) = Gen $ \ k -> g (k . f)

instance Applicative Gen where
  pure a = Gen $ \ k -> k a
  Gen f <*> Gen a = Gen $ \ k -> f (\ g -> a (k . g))

instance Monad Gen where
  Gen g >>= f = Gen $ \ k -> g (\ a -> unGen (f a) k)

runGen :: forall a . Gen (Low a) -> Low a
runGen (Gen f) = f id

-- Bind the code to a variable, so it is evaluated once, and return (code for) the variable.
gen :: forall a . LowRep a => Low a -> Gen (Low a)
gen c = Gen $ \ k -> [| let x = ~c in ~(k [| x |]) |]

-- A recursive definition (a function): the generator gets (code for) the variable being defined.
genRec :: forall a . LowRep a => (Low a -> Low a) -> Gen (Low a)
genRec f = Gen $ \ k -> [| let x = ~(f [| x |]) in ~(k [| x |]) |]

genLet :: forall a b . LowRep a => Low a -> (Low a -> Low b) -> Low b
genLet c f = [| let x = ~c in ~(f [| x |]) |]

-----------------------------------------------------------------------
-- Compile time values as low code.

lowInt :: Int -> Low Int
lowInt i = toLow (HLit (LitInt i) TInt)

lowWord :: Word -> Low Word
lowWord w = toLow (HLit (LitInt (fromIntegral w)) TWord)

lowDouble :: Double -> Low Double
lowDouble d = toLow (HLit (LitDouble d) TDouble)

lowFloat :: Float -> Low Float
lowFloat f = toLow (HLit (LitFloat f) TFloat)

lowChar :: Char -> Low Char
lowChar c = toLow (HLit (LitChar c) TChar)

lowString :: String -> Low String
lowString s = toLow (HLit (LitString s) (lowTyOf s))

lowBool :: Bool -> Low Bool
lowBool True = [| True |]
lowBool False = [| False |]
