-- Closure-free two-level type theory (CFTT, Kovacs ICFP 2024): low code.
--
--   Low a       the meta level type of closure free object code of type a
--
-- Quotations [| e |] and splices ~e are shared with Code (see Staged); a
-- quotation is Low when its type is (Low t).  Low code is a first order,
-- strict, monomorphic subset of Haskell:
--
--  * values have value types: the primitive numeric and character types, and
--    data types whose fields are value types (no functions in data);
--  * functions are first order: the arguments are values (no higher order
--    functions), so no closures are ever needed at run time;
--  * let bound values and function arguments are evaluated (call by value);
--  * class methods are only available at known instances where they are
--    primitives (e.g. + on Int), there is no overloading; other global
--    functions are not available, only constructors and local definitions.
--
-- Low code is generated by ordinary (meta level) Haskell code, which can use
-- all of Haskell; it is in the generated code that functions are first order.
-- Spliced into object code, low code runs as ordinary MicroHs code.
-- With reflect, the generated code is available as a first order syntax tree
-- (LowProg), with the type of every binder, for user written code generators
-- (see Staged.Low.C and Staged.Low.JS).
--
-- A type variable in low code stands for a value type: a generator that is
-- polymorphic in a type that is used in low code needs a (LowRep a) constraint,
-- which the compiler solves for every concrete type.
module Staged.Low(
  Low, LowRep,
  LowTy(..), LowDecl(..), LowConDecl(..), LowCon(..), LowLit(..),
  LowTerm(..), LowProg(..),
  reflect, typeOf, arity, resultType, conFieldTypes, baseName, freeVars,
  lowPretty, lowPrettyTerm,
  Gen(..), runGen, gen, genRec, genLet,
  lowInt, lowWord, lowDouble, lowFloat, lowChar, lowString, lowBool,
  ) where
import Prelude
import Data.List(nub, intercalate)
import Staged.Low.Internal

-----------------------------------------------------------------------
-- First order low code, the result of reflect.

-- Variables are named uniquely in a program; every binder carries its type.
data LowTerm
  = LVar String LowTy                        -- a variable, with its type
  | LLit LowLit LowTy
  | LPrim String LowTy                       -- a primitive of the runtime system (e.g. "+" on Int), with its type
  | LForeign String String LowTy             -- a foreign (C) function: Haskell name, C name, type
  | LApp LowTerm [LowTerm]                   -- a saturated call of a variable, primitive, or foreign function
  | LLam [(String, LowTy)] LowTerm           -- a function; only as the right hand side of a let, or the program
  | LLet String LowTy LowTerm LowTerm        -- let x :: t = e in b  (e is evaluated first, unless it is a function)
  | LLetRec [(String, LowTy, LowTerm)] LowTerm   -- recursive functions
  | LCase LowTerm [LowCon] [(LowCon, [(String, LowTy)], LowTerm)] (Maybe LowTerm)
                                             -- scrutinee, all constructors of its type, alternatives, default
  | LCon LowCon LowTy [LowTerm]              -- a saturated constructor application; the type of the value
  | LFail String                             -- a failed pattern match or error

data LowProg = LowProg {
  progType  :: LowTy,                        -- the type of the program
  progFree  :: [(String, LowTy)],            -- the free (object level) variables
  progDecls :: [LowDecl],                    -- the data types used
  progBody  :: LowTerm
  }

-- The type of a term.
typeOf :: LowTerm -> LowTy
typeOf at =
  case at of
    LVar _ t -> t
    LLit _ t -> t
    LPrim _ t -> t
    LForeign _ _ t -> t
    LApp f as -> applyTy (typeOf f) (length as)
    LLam xs b -> mkFun (map snd xs) (typeOf b)
    LLet _ _ _ b -> typeOf b
    LLetRec _ b -> typeOf b
    LCase _ _ ((_, _, b) : _) _ -> typeOf b
    LCase _ _ [] (Just d) -> typeOf d
    LCase _ _ [] Nothing -> TOther "empty case"
    LCon _ t _ -> t
    LFail _ -> TOther "fail"

-- The number of arguments of a function type.
arity :: LowTy -> Int
arity (TFun as _) = length as
arity _ = 0

resultType :: LowTy -> LowTy
resultType = lowFunResult

applyTy :: LowTy -> Int -> LowTy
applyTy t 0 = t
applyTy (TFun as r) n
  | n < length as = TFun (drop n as) r
  | n == length as = r
  | otherwise = applyTy r (n - length as)
applyTy _ _ = TOther "application of a non-function"

mkFun :: [LowTy] -> LowTy -> LowTy
mkFun [] r = r
mkFun as (TFun bs r) = TFun (as ++ bs) r
mkFun as r = TFun as r

-- The field types of a constructor of a data type (with the type arguments substituted).
conFieldTypes :: LowTy -> LowCon -> [LowTy]
conFieldTypes (TData _ args decl) con =
  case [ conDeclFields c | c <- declCons decl, conDeclTag c == conTag con ] of
    fs : _ -> map (substParams args) fs
    [] -> []
conFieldTypes _ _ = []

substParams :: [LowTy] -> LowTy -> LowTy
substParams args t =
  case t of
    TParam i | i < length args -> args !! i
    TFun as r -> TFun (map (substParams args) as) (substParams args r)
    TData n as d -> TData n (map (substParams args) as) d
    _ -> t

-- The name without the module qualifier.
baseName :: String -> String
baseName s =
  case break (== '.') s of
    (m, '.' : r) | not (null m) && all (\ c -> c /= '(' && c /= '[') m && not (null r) -> baseName r
    _ -> s

-- The free variables of a term.
freeVars :: LowTerm -> [(String, LowTy)]
freeVars = nub . go []
  where
    go bound at =
      case at of
        LVar x t | x `elem` bound -> []
                 | otherwise -> [(x, t)]
        LLit _ _ -> []
        LPrim _ _ -> []
        LForeign _ _ _ -> []
        LApp f as -> concatMap (go bound) (f : as)
        LLam xs b -> go (map fst xs ++ bound) b
        LLet x _ e b -> go bound e ++ go (x : bound) b
        LLetRec bs b -> let bound' = [ x | (x, _, _) <- bs ] ++ bound
                        in concatMap (\ (_, _, e) -> go bound' e) bs ++ go bound' b
        LCase s _ alts d -> go bound s ++ concatMap (\ (_, xs, b) -> go (map fst xs ++ bound) b) alts ++ maybe [] (go bound) d
        LCon _ _ as -> concatMap (go bound) as
        LFail _ -> []

-----------------------------------------------------------------------
-- Reflection: read back the HOAS representation as first order terms.

-- A small state monad: the names in use (with a counter), and the free variables.
newtype R a = R (RS -> (a, RS))
data RS = RS [(String, Int)] [(Int, String, String, LowTy)]

unR :: R a -> RS -> (a, RS)
unR (R f) = f

instance Functor R where
  fmap f (R g) = R $ \ s -> case g s of (a, s') -> (f a, s')
instance Applicative R where
  pure a = R $ \ s -> (a, s)
  R f <*> R a = R $ \ s -> case f s of (g, s') -> case a s' of (b, s'') -> (g b, s'')
instance Monad R where
  R g >>= f = R $ \ s -> case g s of (a, s') -> unR (f a) s'

-- A fresh variable name, based on the name in the source.
fresh :: String -> R String
fresh s = R $ \ (RS ns fs) ->
  let base = case dropWhile (== '$') s of
               "" -> "v"
               b@(c : _) | c >= 'a' && c <= 'z' || c == '_' -> b
                         | otherwise -> "v"
      n = maybe 0 id (lookup base ns)
      ns' = (base, n + 1) : filter ((/= base) . fst) ns
      name = if n == 0 then base else base ++ show n
  in  (name, RS ns' fs)

-- The name of a free (object level) variable.
freeVar :: Int -> String -> LowTy -> R String
freeVar l x t = R $ \ st@(RS _ fs) ->
  case [ n | (l', x', n, _) <- fs, l' == l, x' == x ] of
    n : _ -> (n, st)
    [] -> case unR (fresh x) st of
            (n, RS ns fs') -> (n, RS ns (fs' ++ [(l, x, n, t)]))

-- The level of the variables bound by the read back; the others are free variables.
boundLevel :: Int
boundLevel = -1

readBack :: LowExp -> R LowTerm
readBack ae =
  case ae of
    HVar l x t | l == boundLevel -> return (LVar x t)
               | otherwise -> do { n <- freeVar l x t; return (LVar n t) }
    HLam x t f -> do
      x' <- fresh x
      b <- readBack (f (HVar boundLevel x' t))
      return (LLam [(x', t)] b)
    HApp f as -> LApp <$> readBack f <*> mapM readBack as
    HLet x mt e f -> do
      e' <- readBack e
      let t = maybe (typeOf e') id mt
      x' <- fresh x
      b <- readBack (f (HVar boundLevel x' t))
      return (LLet x' t e' b)
    HLetRec xts f -> do
      xs <- mapM (fresh . fst) xts
      let ts = map snd xts
          (es, b) = f (zipWith (HVar boundLevel) xs ts)
      es' <- mapM readBack es
      b' <- readBack b
      return (LLetRec (zip3 xs ts es') b')
    HCase s cons alts d -> do
      s' <- readBack s
      let st = typeOf s'
          alt (LowAlt con names f) = do
            xs <- mapM fresh names
            let ts = conFieldTypes st con
                ts' = ts ++ replicate (length xs - length ts) (TOther "unknown field type")
            b <- readBack (f (zipWith (HVar boundLevel) xs ts'))
            return (con, zip xs ts', b)
      alts' <- mapM alt alts
      d' <- maybe (return Nothing) (fmap Just . readBack) d
      return (LCase s' cons alts' d')
    HCon c t as -> LCon c t <$> mapM readBack as
    HLit l t -> return (LLit l t)
    HPrim p t -> return (LPrim p t)
    HForeign h c t -> return (LForeign h c t)
    HFail m -> return (LFail m)

-- Call saturation: afterwards every call (LApp) has as many arguments as the
-- function type has, every constructor application is saturated, and functions
-- (LLam) only occur as the right hand side of lets, or as the whole program.
-- (Section 2.2 of the CFTT paper.)
saturate :: LowTerm -> R LowTerm
saturate at =
  case at of
    LApp f as -> do
      f' <- saturate f
      as' <- mapM saturate as
      satApp f' as'
    LLam xs b -> mergeLam xs <$> saturate b
    LLet x t e b -> do
      e' <- saturate e >>= etaTo t
      LLet x t e' <$> saturate b
    LLetRec bs b -> do
      bs' <- mapM (\ (x, t, e) -> do { e' <- saturate e >>= etaTo t; return (x, t, e') }) bs
      LLetRec bs' <$> saturate b
    LCase s cons alts d -> do
      s' <- saturate s
      alts' <- mapM (\ (c, xs, b) -> do { b' <- saturate b; return (c, xs, b') }) alts
      d' <- maybe (return Nothing) (fmap Just . saturate) d
      return (LCase s' cons alts' d')
    LCon c t as -> do
      as' <- mapM saturate as
      let n = conArity c
      if length as' < n then
        etaCon c t as'
       else
        return (LCon c (applyTy t (length as')) as')
    _ -> return at

mergeLam :: [(String, LowTy)] -> LowTerm -> LowTerm
mergeLam xs (LLam ys b) = LLam (xs ++ ys) b
mergeLam xs b = LLam xs b

-- Apply a (saturated) term to (saturated) arguments.
satApp :: LowTerm -> [LowTerm] -> R LowTerm
satApp f [] = return f
satApp f as =
  case f of
    LLam xs b ->
      -- beta: bind the arguments with lets
      let n = min (length xs) (length as)
          binds = zip (take n xs) (take n as)
          rest = drop n xs
          rest' = drop n as
      in  do b' <- if null rest then satApp b rest' else return (LLam rest b)
             return (foldr (\ ((x, t), e) r -> LLet x t e r) b' binds)
    LLet x t e b -> LLet x t e <$> satApp b as
    LLetRec bs b -> LLetRec bs <$> satApp b as
    LCase s cons alts d ->
      -- push the arguments into the alternatives; non-trivial arguments are let bound first
      bindArgs as $ \ vs -> do
        alts' <- mapM (\ (c, xs, b) -> do { b' <- satApp b vs; return (c, xs, b') }) alts
        d' <- maybe (return Nothing) (fmap Just . (`satApp` vs)) d
        return (LCase s cons alts' d')
    LCon c t as' -> saturate (LCon c t (as' ++ as))
    _ -> do
      let n = arity (typeOf f)
      if length as < n then
        etaApp f as
       else if length as == n then
        return (LApp f as)
       else
        satApp (LApp f (take n as)) (drop n as)

bindArgs :: [LowTerm] -> ([LowTerm] -> R LowTerm) -> R LowTerm
bindArgs as k = go [] as
  where
    go acc [] = k (reverse acc)
    go acc (a : rest) =
      case a of
        LVar _ _ -> go (a : acc) rest
        LLit _ _ -> go (a : acc) rest
        _ -> do
          x <- fresh "a"
          let t = typeOf a
          b <- go (LVar x t : acc) rest
          return (LLet x t a b)

-- Eta expand a partial application to a function.
etaApp :: LowTerm -> [LowTerm] -> R LowTerm
etaApp f as =
  case applyTy (typeOf f) (length as) of
    TFun ps _ -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      return (LLam xs (LApp f (as ++ map (\ (v, t) -> LVar v t) xs)))
    _ -> return (LApp f as)

etaCon :: LowCon -> LowTy -> [LowTerm] -> R LowTerm
etaCon c t as =
  case applyTy t (length as) of
    TFun ps r -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      return (LLam xs (LCon c r (as ++ map (\ (v, t') -> LVar v t') xs)))
    _ -> return (LCon c t as)

-- Make a term of function type a lambda.
etaTo :: LowTy -> LowTerm -> R LowTerm
etaTo t e =
  case (t, e) of
    (TFun _ _, LLam _ _) -> return e
    (TFun ps _, _) -> do
      vs <- mapM (const (fresh "x")) ps
      let xs = zip vs ps
      b <- satApp e (map (\ (v, t') -> LVar v t') xs)
      return (mergeLam xs b)
    _ -> return e

-- The declarations of the data types used in a term (and in the types).
collectDecls :: LowTerm -> [LowDecl]
collectDecls t0 = reverse (go [] t0)
  where
    go acc at =
      case at of
        LVar _ t -> ty acc t
        LLit _ t -> ty acc t
        LPrim _ t -> ty acc t
        LForeign _ _ t -> ty acc t
        LApp f as -> foldl go (go acc f) as
        LLam xs b -> go (foldl ty acc (map snd xs)) b
        LLet _ t e b -> go (go (ty acc t) e) b
        LLetRec bs b -> go (foldl (\ a (_, t, e) -> go (ty a t) e) acc bs) b
        LCase s _ alts d -> let acc1 = go acc s
                                acc2 = foldl (\ a (_, xs, b) -> go (foldl ty a (map snd xs)) b) acc1 alts
                            in maybe acc2 (go acc2) d
        LCon _ t as -> foldl go (ty acc t) as
        LFail _ -> acc
    ty acc t =
      case t of
        TFun as r -> foldl ty (ty acc r) as
        TData n as d | n `elem` map declName acc -> foldl ty acc as
                     | otherwise -> foldl ty (foldl ty (d : acc) (concatMap conDeclFields (declCons d))) as
        _ -> acc

-- Reflect low code into a first order program.
reflect :: forall a . Low a -> LowProg
reflect l =
  let act = do
        b <- readBack (fromLow l)
        b' <- saturate b >>= etaTo (typeOf b)
        return b'
      (body, RS _ fs) = unR act (RS [] [])
  in  LowProg { progType = typeOf body
              , progFree = [ (n, t) | (_, _, n, t) <- fs ]
              , progDecls = collectDecls body
              , progBody = body }

-----------------------------------------------------------------------
-- Pretty printing

lowPretty :: LowProg -> String
lowPretty p =
  unlines $
    [ "-- type: " ++ show (progType p) ] ++
    [ "-- free: " ++ x ++ " :: " ++ show t | (x, t) <- progFree p ] ++
    [ "-- " ++ show d | d <- progDecls p ] ++
    [ lowPrettyTerm (progBody p) ]

lowPrettyTerm :: LowTerm -> String
lowPrettyTerm = ppT 0 0

-- precedence: 0 top, 10 argument
ppT :: Int -> Int -> LowTerm -> String
ppT ind p at =
  case at of
    LVar x _ -> x
    LLit l _ -> ppLit l
    LPrim s _ -> s
    LForeign _ c _ -> "ffi:" ++ c
    LApp f as -> par (p > 9) $ unwords (ppT ind 10 f : map (ppT ind 10) as)
    LLam xs b -> par (p > 0) $ "\\ " ++ unwords [ "(" ++ x ++ " :: " ++ show t ++ ")" | (x, t) <- xs ] ++ " ->" ++ nl (ind + 2) ++ ppT (ind + 2) 0 b
    LLet x t e b -> par (p > 0) $ "let " ++ x ++ " :: " ++ show t ++ " = " ++ ppT (ind + 4) 0 e ++ nl ind ++ "in " ++ ppT (ind + 3) 0 b
    LLetRec bs b -> par (p > 0) $ "letrec" ++ concat [ nl (ind + 2) ++ x ++ " :: " ++ show t ++ " = " ++ ppT (ind + 4) 0 e | (x, t, e) <- bs ] ++ nl ind ++ "in " ++ ppT (ind + 3) 0 b
    LCase s _ alts d -> par (p > 0) $ "case " ++ ppT ind 0 s ++ " of" ++
                        concat [ nl (ind + 2) ++ unwords (baseName (conName c) : map fst xs) ++ " -> " ++ ppT (ind + 4) 0 b | (c, xs, b) <- alts ] ++
                        maybe "" (\ e -> nl (ind + 2) ++ "_ -> " ++ ppT (ind + 4) 0 e) d
    LCon c _ [] -> baseName (conName c)
    LCon c _ as -> par (p > 9) $ unwords (baseName (conName c) : map (ppT ind 10) as)
    LFail m -> par (p > 9) $ "fail " ++ show m
  where
    par True s = "(" ++ s ++ ")"
    par False s = s
    nl n = "\n" ++ replicate n ' '

ppLit :: LowLit -> String
ppLit l =
  case l of
    LitInt i -> show i
    LitInt64 i -> show i
    LitDouble d -> show d
    LitFloat f -> show f
    LitChar c -> show c
    LitString s -> show s

-----------------------------------------------------------------------
-- The code generation monad (let insertion), as in Staged, for low code.

newtype Gen a = Gen (forall r . (a -> Low r) -> Low r)

unGen :: forall a r . Gen a -> (a -> Low r) -> Low r
unGen (Gen f) = f

instance Functor Gen where
  fmap f (Gen g) = Gen $ \ k -> g (k . f)

instance Applicative Gen where
  pure a = Gen $ \ k -> k a
  Gen f <*> Gen a = Gen $ \ k -> f (\ g -> a (k . g))

instance Monad Gen where
  Gen g >>= f = Gen $ \ k -> g (\ a -> unGen (f a) k)

runGen :: forall a . Gen (Low a) -> Low a
runGen (Gen f) = f id

-- Bind the code to a variable, so it is evaluated once, and return (code for) the variable.
gen :: forall a . LowRep a => Low a -> Gen (Low a)
gen c = Gen $ \ k -> [| let x = ~c in ~(k [| x |]) |]

-- A recursive definition (a function): the generator gets (code for) the variable being defined.
genRec :: forall a . LowRep a => (Low a -> Low a) -> Gen (Low a)
genRec f = Gen $ \ k -> [| let x = ~(f [| x |]) in ~(k [| x |]) |]

genLet :: forall a b . LowRep a => Low a -> (Low a -> Low b) -> Low b
genLet c f = [| let x = ~c in ~(f [| x |]) |]

-----------------------------------------------------------------------
-- Compile time values as low code.

lowInt :: Int -> Low Int
lowInt i = toLow (HLit (LitInt i) TInt)

lowWord :: Word -> Low Word
lowWord w = toLow (HLit (LitInt (fromIntegral w)) TWord)

lowDouble :: Double -> Low Double
lowDouble d = toLow (HLit (LitDouble d) TDouble)

lowFloat :: Float -> Low Float
lowFloat f = toLow (HLit (LitFloat f) TFloat)

lowChar :: Char -> Low Char
lowChar c = toLow (HLit (LitChar c) TChar)

lowString :: String -> Low String
lowString s = toLow (HLit (LitString s) (lowTyOf s))

lowBool :: Bool -> Low Bool
lowBool True = [| True |]
lowBool False = [| False |]
