/* Generated by tests/LowFutamura.hs (see LowFutamura.ref), formatted with clang-format:
 *
 *   pfactorial :: Low (Int -> Int)
 *   pfactorial = evalFun (deBruijn factorial)
 *
 * the call by need lambda calculus interpreter, run at compile time on the
 * factorial program (the Y combinator applied to \ fact n -> ...).
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

/* Data.Bool_Type.Bool: False=0, True=1 */

static int64_t f(int64_t a);
static int64_t f(int64_t a) {
  int64_t r_0;
  switch ((a == 0)) {
  case 0: {
    int64_t x = (a - 1);
    int64_t x_1 = f(x);
    int64_t x_2 = (a * x_1);
    r_0 = x_2;
    break;
  }
  case 1: {
    r_0 = 1;
    break;
  }
  default:
    abort();
  }
  return r_0;
}

int64_t pfactorial(int64_t n) { return f(n); }
