/* Generated by tests/LowFutamuraLazy.hs (see LowFutamuraLazy.ref), printed by tests/LowCompactC.hs:
 *
 *   fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
 *   pfibs input = fibs !! input
 *
 * the staged call by need interpreter applied to the program, with the
 * linearly threaded heap state printed as a global mutable heap.
 */
#include <stdint.h>
#include <stdlib.h>
typedef struct Cell Cell; typedef struct Ints Ints; typedef struct RV RV;
struct Cell { int tag; union { struct { int64_t f0; Ints * f1; } Thunk; struct { RV * f0; } Done; } u; };
struct Ints { int tag; union { struct { int64_t f0; Ints * f1; } ICons; } u; };
struct RV { int tag; union { struct { int64_t f0; } RInt; struct { int64_t f0; int64_t f1; } RCons; } u; };
static Cell *C_Thunk(int64_t a0, Ints * a1) { Cell *p = malloc(sizeof *p); p->tag = 0; p->u.Thunk.f0 = a0; p->u.Thunk.f1 = a1; return p; }
static Cell *C_Done(RV * a0) { Cell *p = malloc(sizeof *p); p->tag = 1; p->u.Done.f0 = a0; return p; }
static Ints *C_INil(void) { Ints *p = malloc(sizeof *p); p->tag = 0; return p; }
static Ints *C_ICons(int64_t a0, Ints * a1) { Ints *p = malloc(sizeof *p); p->tag = 1; p->u.ICons.f0 = a0; p->u.ICons.f1 = a1; return p; }
static RV *C_RInt(int64_t a0) { RV *p = malloc(sizeof *p); p->tag = 0; p->u.RInt.f0 = a0; return p; }
static RV *C_RNil(void) { RV *p = malloc(sizeof *p); p->tag = 1; return p; }
static RV *C_RCons(int64_t a0, int64_t a1) { RV *p = malloc(sizeof *p); p->tag = 2; p->u.RCons.f0 = a0; p->u.RCons.f1 = a1; return p; }
static Cell *heap[1 << 20]; static int64_t hp;
static int64_t alloc(Cell *c) { heap[hp] = c; return hp++; }
static RV * x_2(int64_t c_1, int64_t a_2, Ints * xs);
static RV * j(int64_t a0_33, int64_t x4_16, RV * v) {
  if (v->tag == 1) return C_RNil();
  int64_t a0_37 = alloc(C_Thunk(3, C_ICons(v->u.RCons.f0, C_ICons(a0_33, C_INil()))));
  int64_t a0_39 = alloc(C_Thunk(4, C_ICons(v->u.RCons.f1, C_ICons(x4_16, C_INil()))));
  return C_RCons(a0_37, a0_39);
}
static RV * x_2(int64_t c_1, int64_t a_2, Ints * xs) {
  if ((c_1 == 0)) {
    Cell * x1_31 = heap[a_2];
    if (x1_31->tag == 1) return x1_31->u.Done.f0;
    RV * x1_32 = x_2((x1_31->u.Thunk.f0 + 1), 0, x1_31->u.Thunk.f1);
    heap[a_2] = C_Done(x1_32);
    return x1_32;
  } else {
    int64_t d = (c_1 - 1);
    if ((d == 0)) {
      int64_t a0_53 = alloc(C_Done(C_RInt(0)));
      int64_t a0_55 = alloc(C_Thunk(1, C_ICons(xs->u.ICons.f0, C_INil())));
      return C_RCons(a0_53, a0_55);
    } else if ((d == 1)) {
      int64_t a0_47 = alloc(C_Done(C_RInt(1)));
      int64_t a0_49 = alloc(C_Thunk(2, C_ICons(xs->u.ICons.f0, C_INil())));
      return C_RCons(a0_47, a0_49);
    } else if ((d == 2)) {
      RV * x1_17 = x_2(0, xs->u.ICons.f0, C_INil());
      if (x1_17->tag == 1) return C_RNil();
      RV * x1_23 = x_2(0, x1_17->u.RCons.f1, C_INil());
      return j(x1_17->u.RCons.f0, x1_17->u.RCons.f1, x1_23);
    } else if ((d == 3)) {
      Ints * s0 = xs->u.ICons.f1;
      RV * x1_12 = x_2(0, s0->u.ICons.f0, C_INil());
      RV * x1_13 = x_2(0, xs->u.ICons.f0, C_INil());
      return C_RInt((x1_12->u.RInt.f0 + x1_13->u.RInt.f0));
    } else {
      Ints * s1 = xs->u.ICons.f1;
      RV * x1_4 = x_2(0, s1->u.ICons.f0, C_INil());
      if (x1_4->tag == 1) return C_RNil();
      RV * x1_6 = x_2(0, xs->u.ICons.f0, C_INil());
      if (x1_6->tag == 1) return C_RNil();
      int64_t a0_13 = alloc(C_Thunk(3, C_ICons(x1_6->u.RCons.f0, C_ICons(x1_4->u.RCons.f0, C_INil()))));
      int64_t a0_15 = alloc(C_Thunk(4, C_ICons(x1_6->u.RCons.f1, C_ICons(x1_4->u.RCons.f1, C_INil()))));
      return C_RCons(a0_13, a0_15);
    }
  }
}
static RV * f(int64_t a_3, int64_t b);
static RV * f(int64_t a_3, int64_t b) {
  if ((b == 0)) {
    RV * x1_38 = x_2(0, a_3, C_INil());
    if (x1_38->tag == 1) return C_RInt(0);
    return x_2(0, x1_38->u.RCons.f0, C_INil());
  } else {
    RV * x1_36 = x_2(0, a_3, C_INil());
    if (x1_36->tag == 1) return C_RInt(0);
    return f(x1_36->u.RCons.f1, (b - 1));
  }
}
int64_t pfibs(int64_t n) {
  RV * x1_40;
  hp = 1;
  int64_t a0_58 = alloc(C_Done(C_RNil()));
  heap[a0_58] = C_Thunk(0, C_ICons(a0_58, C_INil()));
  x1_40 = f(a0_58, n);
  return x1_40->u.RInt.f0;
}
