/* Generated by tests/LowFutamuraLazy.hs (see LowFutamuraLazy.ref), formatted with clang-format:
 *
 *   fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
 *   pfibs input = fibs !! input
 *
 * the call by need interpreter, run at compile time on the program: a heap of
 * cells for the list, and run, the code of its thunks by number.
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

struct Cell {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Ints *f1;
    } Thunk;
    struct {
      struct RV *f0;
    } Done;
  } u;
};
struct Ints {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Ints *f1;
    } ICons;
  } u;
};
struct RV {
  int tag;
  union {
    struct {
      int64_t f0;
    } RInt;
    struct {
      int64_t f0;
      int64_t f1;
    } RCons;
  } u;
};
struct Heap {
  int tag;
  union {
    struct {
      struct Heap *f0;
      struct Cell *f1;
      struct Heap *f2;
    } Node;
  } u;
};
/* Data.Bool_Type.Bool: False=0, True=1 */
struct Res {
  int tag;
  union {
    struct {
      struct RV *f0;
      struct St *f1;
    } Res;
  } u;
};
struct St {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Heap *f1;
    } St;
  } u;
};

static struct Cell *x(struct Heap *h, int64_t a);
static struct Cell *x(struct Heap *h, int64_t a) {
  struct Cell *r_0;
  switch (h->tag) {
  case 1: {
    struct Heap *x3 = h->u.Node.f0;
    struct Cell *x4 = h->u.Node.f1;
    struct Heap *x5 = h->u.Node.f2;
    struct Cell *r_1;
    switch ((a == 1)) {
    case 0: {
      struct Cell *r_2;
      switch (((a - (2 * (a / 2))) == 0)) {
      case 0: {
        r_2 = x(x5, (a / 2));
        break;
      }
      case 1: {
        r_2 = x(x3, (a / 2));
        break;
      }
      default:
        abort();
      }
      r_1 = r_2;
      break;
    }
    case 1: {
      r_1 = x4;
      break;
    }
    default:
      abort();
    }
    r_0 = r_1;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",749:27");
    abort();
    r_0 = 0;
    break;
  }
  }
  return r_0;
}
static struct Heap *x_1(struct Heap *h_1, int64_t a_1, struct Cell *c);
static struct Heap *x_1(struct Heap *h_1, int64_t a_1, struct Cell *c) {
  struct Heap *r_3;
  switch (h_1->tag) {
  case 0: {
    struct Heap *c_4 = malloc(sizeof(struct Heap));
    c_4->tag = 0;
    struct Heap *c_5 = malloc(sizeof(struct Heap));
    c_5->tag = 0;
    struct Heap *c_6 = malloc(sizeof(struct Heap));
    c_6->tag = 1;
    c_6->u.Node.f0 = c_4;
    c_6->u.Node.f1 = c;
    c_6->u.Node.f2 = c_5;
    r_3 = c_6;
    break;
  }
  case 1: {
    struct Heap *x3_1 = h_1->u.Node.f0;
    struct Cell *x4_1 = h_1->u.Node.f1;
    struct Heap *x5_1 = h_1->u.Node.f2;
    struct Heap *r_7;
    switch ((a_1 == 1)) {
    case 0: {
      struct Heap *r_8;
      switch (((a_1 - (2 * (a_1 / 2))) == 0)) {
      case 0: {
        struct Heap *c_9 = malloc(sizeof(struct Heap));
        c_9->tag = 1;
        c_9->u.Node.f0 = x3_1;
        c_9->u.Node.f1 = x4_1;
        c_9->u.Node.f2 = x_1(x5_1, (a_1 / 2), c);
        r_8 = c_9;
        break;
      }
      case 1: {
        struct Heap *c_10 = malloc(sizeof(struct Heap));
        c_10->tag = 1;
        c_10->u.Node.f0 = x_1(x3_1, (a_1 / 2), c);
        c_10->u.Node.f1 = x4_1;
        c_10->u.Node.f2 = x5_1;
        r_8 = c_10;
        break;
      }
      default:
        abort();
      }
      r_7 = r_8;
      break;
    }
    case 1: {
      struct Heap *c_11 = malloc(sizeof(struct Heap));
      c_11->tag = 1;
      c_11->u.Node.f0 = x3_1;
      c_11->u.Node.f1 = c;
      c_11->u.Node.f2 = x5_1;
      r_7 = c_11;
      break;
    }
    default:
      abort();
    }
    r_3 = r_7;
    break;
  }
  default:
    abort();
  }
  return r_3;
}
static struct Res *x_2(int64_t c_1, struct Ints *xs, struct St *st);
static struct Res *j(int64_t a0_5, int64_t a1_2, struct RV *v_1, struct St *s_1) {
  struct Res *r_24;
  switch (v_1->tag) {
  case 1: {
    struct RV *c_25 = malloc(sizeof(struct RV));
    c_25->tag = 1;
    struct RV *x_4 = c_25;
    struct Res *c_26 = malloc(sizeof(struct Res));
    c_26->tag = 0;
    c_26->u.Res.f0 = x_4;
    c_26->u.Res.f1 = s_1;
    r_24 = c_26;
    break;
  }
  case 2: {
    int64_t a0_7 = v_1->u.RCons.f0;
    int64_t a1_3 = v_1->u.RCons.f1;
    struct Res *r_27;
    switch (s_1->tag) {
    case 0: {
      int64_t a0_9 = s_1->u.St.f0;
      struct Heap *a1_4 = s_1->u.St.f1;
      struct Ints *c_28 = malloc(sizeof(struct Ints));
      c_28->tag = 0;
      struct Ints *c_29 = malloc(sizeof(struct Ints));
      c_29->tag = 1;
      c_29->u.ICons.f0 = a0_5;
      c_29->u.ICons.f1 = c_28;
      struct Ints *c_30 = malloc(sizeof(struct Ints));
      c_30->tag = 1;
      c_30->u.ICons.f0 = a0_7;
      c_30->u.ICons.f1 = c_29;
      struct Cell *c_31 = malloc(sizeof(struct Cell));
      c_31->tag = 0;
      c_31->u.Thunk.f0 = 6;
      c_31->u.Thunk.f1 = c_30;
      struct St *c_32 = malloc(sizeof(struct St));
      c_32->tag = 0;
      c_32->u.St.f0 = (a0_9 + 1);
      c_32->u.St.f1 = x_1(a1_4, a0_9, c_31);
      struct St *s1 = c_32;
      struct Res *r_33;
      switch (s1->tag) {
      case 0: {
        int64_t a0_11 = s1->u.St.f0;
        struct Heap *a1_5 = s1->u.St.f1;
        struct Ints *c_34 = malloc(sizeof(struct Ints));
        c_34->tag = 0;
        struct Ints *c_35 = malloc(sizeof(struct Ints));
        c_35->tag = 1;
        c_35->u.ICons.f0 = a1_2;
        c_35->u.ICons.f1 = c_34;
        struct Ints *c_36 = malloc(sizeof(struct Ints));
        c_36->tag = 1;
        c_36->u.ICons.f0 = a1_3;
        c_36->u.ICons.f1 = c_35;
        struct Cell *c_37 = malloc(sizeof(struct Cell));
        c_37->tag = 0;
        c_37->u.Thunk.f0 = 7;
        c_37->u.Thunk.f1 = c_36;
        struct St *c_38 = malloc(sizeof(struct St));
        c_38->tag = 0;
        c_38->u.St.f0 = (a0_11 + 1);
        c_38->u.St.f1 = x_1(a1_5, a0_11, c_37);
        struct St *s1_1 = c_38;
        struct RV *c_39 = malloc(sizeof(struct RV));
        c_39->tag = 2;
        c_39->u.RCons.f0 = a0_9;
        c_39->u.RCons.f1 = a0_11;
        struct RV *x_5 = c_39;
        struct Res *c_40 = malloc(sizeof(struct Res));
        c_40->tag = 0;
        c_40->u.Res.f0 = x_5;
        c_40->u.Res.f1 = s1_1;
        r_33 = c_40;
        break;
      }
      default:
        abort();
      }
      r_27 = r_33;
      break;
    }
    default:
      abort();
    }
    r_24 = r_27;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_24 = 0;
    break;
  }
  }
  return r_24;
}
static struct Res *j_1(int64_t a0_1, struct RV *v, struct St *s) {
  struct Res *r_21;
  switch (v->tag) {
  case 1: {
    struct RV *c_22 = malloc(sizeof(struct RV));
    c_22->tag = 1;
    struct RV *x_3 = c_22;
    struct Res *c_23 = malloc(sizeof(struct Res));
    c_23->tag = 0;
    c_23->u.Res.f0 = x_3;
    c_23->u.Res.f1 = s;
    r_21 = c_23;
    break;
  }
  case 2: {
    int64_t a0_5 = v->u.RCons.f0;
    int64_t a1_2 = v->u.RCons.f1;
    struct Res *r_41;
    switch (s->tag) {
    case 0: {
      int64_t a4 = s->u.St.f0;
      struct Heap *a4_1 = s->u.St.f1;
      struct Cell *x1_9 = x(a4_1, a0_1);
      struct Res *r_42;
      switch (x1_9->tag) {
      case 1: {
        struct RV *a0_12 = x1_9->u.Done.f0;
        r_42 = j(a0_5, a1_2, a0_12, s);
        break;
      }
      case 0: {
        int64_t x5_2 = x1_9->u.Thunk.f0;
        struct Ints *x6 = x1_9->u.Thunk.f1;
        struct Res *x1_10 = x_2(x5_2, x6, s);
        struct Res *r_43;
        switch (x1_10->tag) {
        case 0: {
          struct RV *a3_3 = x1_10->u.Res.f0;
          struct St *a2 = x1_10->u.Res.f1;
          struct Res *r_44;
          switch (a2->tag) {
          case 0: {
            int64_t a0_13 = a2->u.St.f0;
            struct Heap *a1_6 = a2->u.St.f1;
            struct Cell *c_45 = malloc(sizeof(struct Cell));
            c_45->tag = 1;
            c_45->u.Done.f0 = a3_3;
            struct St *c_46 = malloc(sizeof(struct St));
            c_46->tag = 0;
            c_46->u.St.f0 = a0_13;
            c_46->u.St.f1 = x_1(a1_6, a0_1, c_45);
            r_44 = j(a0_5, a1_2, a3_3, c_46);
            break;
          }
          default:
            abort();
          }
          r_43 = r_44;
          break;
        }
        default:
          abort();
        }
        r_42 = r_43;
        break;
      }
      default:
        abort();
      }
      r_41 = r_42;
      break;
    }
    default:
      abort();
    }
    r_21 = r_41;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_21 = 0;
    break;
  }
  }
  return r_21;
}
static struct Res *j_2(struct RV *v_2, struct RV *v_3, struct St *s_3) {
  struct Res *r_55;
  switch (v_2->tag) {
  case 0: {
    int64_t a0_21 = v_2->u.RInt.f0;
    struct Res *r_56;
    switch (v_3->tag) {
    case 0: {
      int64_t a0_23 = v_3->u.RInt.f0;
      int64_t x_6 = (a0_21 + a0_23);
      struct RV *c_57 = malloc(sizeof(struct RV));
      c_57->tag = 0;
      c_57->u.RInt.f0 = x_6;
      struct Res *c_58 = malloc(sizeof(struct Res));
      c_58->tag = 0;
      c_58->u.Res.f0 = c_57;
      c_58->u.Res.f1 = s_3;
      r_56 = c_58;
      break;
    }
    default: {
      fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",325:32");
      abort();
      r_56 = 0;
      break;
    }
    }
    r_55 = r_56;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",325:32");
    abort();
    r_55 = 0;
    break;
  }
  }
  return r_55;
}
static struct Res *j_3(int64_t a0_17, struct RV *v_2, struct St *s_2) {
  struct Res *r_59;
  switch (s_2->tag) {
  case 0: {
    int64_t a4_4 = s_2->u.St.f0;
    struct Heap *a4_5 = s_2->u.St.f1;
    struct Cell *x1_21 = x(a4_5, a0_17);
    struct Res *r_60;
    switch (x1_21->tag) {
    case 1: {
      struct RV *a0_24 = x1_21->u.Done.f0;
      r_60 = j_2(v_2, a0_24, s_2);
      break;
    }
    case 0: {
      int64_t x5_4 = x1_21->u.Thunk.f0;
      struct Ints *x6_2 = x1_21->u.Thunk.f1;
      struct Res *x1_22 = x_2(x5_4, x6_2, s_2);
      struct Res *r_61;
      switch (x1_22->tag) {
      case 0: {
        struct RV *a3_11 = x1_22->u.Res.f0;
        struct St *a2_4 = x1_22->u.Res.f1;
        struct Res *r_62;
        switch (a2_4->tag) {
        case 0: {
          int64_t a0_25 = a2_4->u.St.f0;
          struct Heap *a1_10 = a2_4->u.St.f1;
          struct Cell *c_63 = malloc(sizeof(struct Cell));
          c_63->tag = 1;
          c_63->u.Done.f0 = a3_11;
          struct St *c_64 = malloc(sizeof(struct St));
          c_64->tag = 0;
          c_64->u.St.f0 = a0_25;
          c_64->u.St.f1 = x_1(a1_10, a0_17, c_63);
          r_62 = j_2(v_2, a3_11, c_64);
          break;
        }
        default:
          abort();
        }
        r_61 = r_62;
        break;
      }
      default:
        abort();
      }
      r_60 = r_61;
      break;
    }
    default:
      abort();
    }
    r_59 = r_60;
    break;
  }
  default:
    abort();
  }
  return r_59;
}
static struct Res *j_4(int64_t a0_31, int64_t a1_13, struct RV *v_5, struct St *s_5) {
  struct Res *r_75;
  switch (v_5->tag) {
  case 1: {
    struct RV *c_76 = malloc(sizeof(struct RV));
    c_76->tag = 1;
    struct RV *x_8 = c_76;
    struct Res *c_77 = malloc(sizeof(struct Res));
    c_77->tag = 0;
    c_77->u.Res.f0 = x_8;
    c_77->u.Res.f1 = s_5;
    r_75 = c_77;
    break;
  }
  case 2: {
    int64_t a0_33 = v_5->u.RCons.f0;
    int64_t a1_14 = v_5->u.RCons.f1;
    struct Res *r_78;
    switch (s_5->tag) {
    case 0: {
      int64_t a0_35 = s_5->u.St.f0;
      struct Heap *a1_15 = s_5->u.St.f1;
      struct Ints *c_79 = malloc(sizeof(struct Ints));
      c_79->tag = 0;
      struct Ints *c_80 = malloc(sizeof(struct Ints));
      c_80->tag = 1;
      c_80->u.ICons.f0 = a0_31;
      c_80->u.ICons.f1 = c_79;
      struct Ints *c_81 = malloc(sizeof(struct Ints));
      c_81->tag = 1;
      c_81->u.ICons.f0 = a0_33;
      c_81->u.ICons.f1 = c_80;
      struct Cell *c_82 = malloc(sizeof(struct Cell));
      c_82->tag = 0;
      c_82->u.Thunk.f0 = 6;
      c_82->u.Thunk.f1 = c_81;
      struct St *c_83 = malloc(sizeof(struct St));
      c_83->tag = 0;
      c_83->u.St.f0 = (a0_35 + 1);
      c_83->u.St.f1 = x_1(a1_15, a0_35, c_82);
      struct St *s1_2 = c_83;
      struct Res *r_84;
      switch (s1_2->tag) {
      case 0: {
        int64_t a0_37 = s1_2->u.St.f0;
        struct Heap *a1_16 = s1_2->u.St.f1;
        struct Ints *c_85 = malloc(sizeof(struct Ints));
        c_85->tag = 0;
        struct Ints *c_86 = malloc(sizeof(struct Ints));
        c_86->tag = 1;
        c_86->u.ICons.f0 = a1_13;
        c_86->u.ICons.f1 = c_85;
        struct Ints *c_87 = malloc(sizeof(struct Ints));
        c_87->tag = 1;
        c_87->u.ICons.f0 = a1_14;
        c_87->u.ICons.f1 = c_86;
        struct Cell *c_88 = malloc(sizeof(struct Cell));
        c_88->tag = 0;
        c_88->u.Thunk.f0 = 7;
        c_88->u.Thunk.f1 = c_87;
        struct St *c_89 = malloc(sizeof(struct St));
        c_89->tag = 0;
        c_89->u.St.f0 = (a0_37 + 1);
        c_89->u.St.f1 = x_1(a1_16, a0_37, c_88);
        struct St *s1_3 = c_89;
        struct RV *c_90 = malloc(sizeof(struct RV));
        c_90->tag = 2;
        c_90->u.RCons.f0 = a0_35;
        c_90->u.RCons.f1 = a0_37;
        struct RV *x_9 = c_90;
        struct Res *c_91 = malloc(sizeof(struct Res));
        c_91->tag = 0;
        c_91->u.Res.f0 = x_9;
        c_91->u.Res.f1 = s1_3;
        r_84 = c_91;
        break;
      }
      default:
        abort();
      }
      r_78 = r_84;
      break;
    }
    default:
      abort();
    }
    r_75 = r_78;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_75 = 0;
    break;
  }
  }
  return r_75;
}
static struct Res *j_5(int64_t a0_31, int64_t a1_13, struct RV *v_6, struct St *s_6) {
  return j_4(a0_31, a1_13, v_6, s_6);
}
static struct Res *j_6(struct RV *v_4, struct St *s_4) {
  struct Res *r_72;
  switch (v_4->tag) {
  case 1: {
    struct RV *c_73 = malloc(sizeof(struct RV));
    c_73->tag = 1;
    struct RV *x_7 = c_73;
    struct Res *c_74 = malloc(sizeof(struct Res));
    c_74->tag = 0;
    c_74->u.Res.f0 = x_7;
    c_74->u.Res.f1 = s_4;
    r_72 = c_74;
    break;
  }
  case 2: {
    int64_t a0_31 = v_4->u.RCons.f0;
    int64_t a1_13 = v_4->u.RCons.f1;
    struct Res *r_92;
    switch (v_4->tag) {
    case 1: {
      struct RV *c_93 = malloc(sizeof(struct RV));
      c_93->tag = 1;
      struct RV *x_10 = c_93;
      r_92 = j_4(a0_31, a1_13, x_10, s_4);
      break;
    }
    case 2: {
      int64_t a0_39 = v_4->u.RCons.f0;
      int64_t a1_17 = v_4->u.RCons.f1;
      struct Res *r_94;
      switch (s_4->tag) {
      case 0: {
        int64_t a4_8 = s_4->u.St.f0;
        struct Heap *a4_9 = s_4->u.St.f1;
        struct Cell *x1_35 = x(a4_9, a1_17);
        struct Res *r_95;
        switch (x1_35->tag) {
        case 1: {
          struct RV *a0_40 = x1_35->u.Done.f0;
          r_95 = j_5(a0_31, a1_13, a0_40, s_4);
          break;
        }
        case 0: {
          int64_t x5_6 = x1_35->u.Thunk.f0;
          struct Ints *x6_4 = x1_35->u.Thunk.f1;
          struct Res *x1_36 = x_2(x5_6, x6_4, s_4);
          struct Res *r_96;
          switch (x1_36->tag) {
          case 0: {
            struct RV *a3_19 = x1_36->u.Res.f0;
            struct St *a2_8 = x1_36->u.Res.f1;
            struct Res *r_97;
            switch (a2_8->tag) {
            case 0: {
              int64_t a0_41 = a2_8->u.St.f0;
              struct Heap *a1_18 = a2_8->u.St.f1;
              struct Cell *c_98 = malloc(sizeof(struct Cell));
              c_98->tag = 1;
              c_98->u.Done.f0 = a3_19;
              struct St *c_99 = malloc(sizeof(struct St));
              c_99->tag = 0;
              c_99->u.St.f0 = a0_41;
              c_99->u.St.f1 = x_1(a1_18, a1_17, c_98);
              r_97 = j_5(a0_31, a1_13, a3_19, c_99);
              break;
            }
            default:
              abort();
            }
            r_96 = r_97;
            break;
          }
          default:
            abort();
          }
          r_95 = r_96;
          break;
        }
        default:
          abort();
        }
        r_94 = r_95;
        break;
      }
      default:
        abort();
      }
      r_92 = r_94;
      break;
    }
    default: {
      fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
      abort();
      r_92 = 0;
      break;
    }
    }
    r_72 = r_92;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_72 = 0;
    break;
  }
  }
  return r_72;
}
static struct Res *j_7(struct RV *v_7, struct St *s_7) {
  struct Res *r_119;
  switch (v_7->tag) {
  case 0: {
    int64_t a0_53 = v_7->u.RInt.f0;
    int64_t x_12 = (a0_53 - 1);
    struct RV *c_120 = malloc(sizeof(struct RV));
    c_120->tag = 0;
    c_120->u.RInt.f0 = x_12;
    struct Res *c_121 = malloc(sizeof(struct Res));
    c_121->tag = 0;
    c_121->u.Res.f0 = c_120;
    c_121->u.Res.f1 = s_7;
    r_119 = c_121;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",325:32");
    abort();
    r_119 = 0;
    break;
  }
  }
  return r_119;
}
static struct Res *x_2(int64_t c_1, struct Ints *xs, struct St *st) {
  struct Res *r_12;
  switch ((c_1 == 0)) {
  case 0: {
    struct Res *r_13;
    switch ((c_1 == 1)) {
    case 0: {
      struct Res *r_14;
      switch ((c_1 == 2)) {
      case 0: {
        struct Res *r_15;
        switch ((c_1 == 3)) {
        case 0: {
          struct Res *r_16;
          switch ((c_1 == 4)) {
          case 0: {
            struct Res *r_17;
            switch ((c_1 == 5)) {
            case 0: {
              struct Res *r_18;
              switch ((c_1 == 6)) {
              case 0: {
                struct Res *r_19;
                switch (xs->tag) {
                case 1: {
                  int64_t a0_1 = xs->u.ICons.f0;
                  struct Ints *a1 = xs->u.ICons.f1;
                  struct Res *r_20;
                  switch (a1->tag) {
                  case 1: {
                    int64_t a0_3 = a1->u.ICons.f0;
                    struct Ints *a1_1 = a1->u.ICons.f1;
                    struct Res *r_47;
                    switch (st->tag) {
                    case 0: {
                      int64_t a4_2 = st->u.St.f0;
                      struct Heap *a4_3 = st->u.St.f1;
                      struct Cell *x1_13 = x(a4_3, a0_3);
                      struct Res *r_48;
                      switch (x1_13->tag) {
                      case 1: {
                        struct RV *a0_14 = x1_13->u.Done.f0;
                        r_48 = j_1(a0_1, a0_14, st);
                        break;
                      }
                      case 0: {
                        int64_t x5_3 = x1_13->u.Thunk.f0;
                        struct Ints *x6_1 = x1_13->u.Thunk.f1;
                        struct Res *x1_14 = x_2(x5_3, x6_1, st);
                        struct Res *r_49;
                        switch (x1_14->tag) {
                        case 0: {
                          struct RV *a3_7 = x1_14->u.Res.f0;
                          struct St *a2_2 = x1_14->u.Res.f1;
                          struct Res *r_50;
                          switch (a2_2->tag) {
                          case 0: {
                            int64_t a0_15 = a2_2->u.St.f0;
                            struct Heap *a1_7 = a2_2->u.St.f1;
                            struct Cell *c_51 = malloc(sizeof(struct Cell));
                            c_51->tag = 1;
                            c_51->u.Done.f0 = a3_7;
                            struct St *c_52 = malloc(sizeof(struct St));
                            c_52->tag = 0;
                            c_52->u.St.f0 = a0_15;
                            c_52->u.St.f1 = x_1(a1_7, a0_3, c_51);
                            r_50 = j_1(a0_1, a3_7, c_52);
                            break;
                          }
                          default:
                            abort();
                          }
                          r_49 = r_50;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_48 = r_49;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_47 = r_48;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_20 = r_47;
                    break;
                  }
                  default: {
                    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
                    abort();
                    r_20 = 0;
                    break;
                  }
                  }
                  r_19 = r_20;
                  break;
                }
                default: {
                  fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
                  abort();
                  r_19 = 0;
                  break;
                }
                }
                r_18 = r_19;
                break;
              }
              case 1: {
                struct Res *r_53;
                switch (xs->tag) {
                case 1: {
                  int64_t a0_17 = xs->u.ICons.f0;
                  struct Ints *a1_8 = xs->u.ICons.f1;
                  struct Res *r_54;
                  switch (a1_8->tag) {
                  case 1: {
                    int64_t a0_19 = a1_8->u.ICons.f0;
                    struct Ints *a1_9 = a1_8->u.ICons.f1;
                    struct Res *r_65;
                    switch (st->tag) {
                    case 0: {
                      int64_t a4_6 = st->u.St.f0;
                      struct Heap *a4_7 = st->u.St.f1;
                      struct Cell *x1_25 = x(a4_7, a0_19);
                      struct Res *r_66;
                      switch (x1_25->tag) {
                      case 1: {
                        struct RV *a0_26 = x1_25->u.Done.f0;
                        r_66 = j_3(a0_17, a0_26, st);
                        break;
                      }
                      case 0: {
                        int64_t x5_5 = x1_25->u.Thunk.f0;
                        struct Ints *x6_3 = x1_25->u.Thunk.f1;
                        struct Res *x1_26 = x_2(x5_5, x6_3, st);
                        struct Res *r_67;
                        switch (x1_26->tag) {
                        case 0: {
                          struct RV *a3_15 = x1_26->u.Res.f0;
                          struct St *a2_6 = x1_26->u.Res.f1;
                          struct Res *r_68;
                          switch (a2_6->tag) {
                          case 0: {
                            int64_t a0_27 = a2_6->u.St.f0;
                            struct Heap *a1_11 = a2_6->u.St.f1;
                            struct Cell *c_69 = malloc(sizeof(struct Cell));
                            c_69->tag = 1;
                            c_69->u.Done.f0 = a3_15;
                            struct St *c_70 = malloc(sizeof(struct St));
                            c_70->tag = 0;
                            c_70->u.St.f0 = a0_27;
                            c_70->u.St.f1 = x_1(a1_11, a0_19, c_69);
                            r_68 = j_3(a0_17, a3_15, c_70);
                            break;
                          }
                          default:
                            abort();
                          }
                          r_67 = r_68;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_66 = r_67;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_65 = r_66;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_54 = r_65;
                    break;
                  }
                  default: {
                    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
                    abort();
                    r_54 = 0;
                    break;
                  }
                  }
                  r_53 = r_54;
                  break;
                }
                default: {
                  fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
                  abort();
                  r_53 = 0;
                  break;
                }
                }
                r_18 = r_53;
                break;
              }
              default:
                abort();
              }
              r_17 = r_18;
              break;
            }
            case 1: {
              struct Res *r_71;
              switch (xs->tag) {
              case 1: {
                int64_t a0_29 = xs->u.ICons.f0;
                struct Ints *a1_12 = xs->u.ICons.f1;
                struct Res *r_100;
                switch (st->tag) {
                case 0: {
                  int64_t a4_10 = st->u.St.f0;
                  struct Heap *a4_11 = st->u.St.f1;
                  struct Cell *x1_39 = x(a4_11, a0_29);
                  struct Res *r_101;
                  switch (x1_39->tag) {
                  case 1: {
                    struct RV *a0_42 = x1_39->u.Done.f0;
                    r_101 = j_6(a0_42, st);
                    break;
                  }
                  case 0: {
                    int64_t x5_7 = x1_39->u.Thunk.f0;
                    struct Ints *x6_5 = x1_39->u.Thunk.f1;
                    struct Res *x1_40 = x_2(x5_7, x6_5, st);
                    struct Res *r_102;
                    switch (x1_40->tag) {
                    case 0: {
                      struct RV *a3_23 = x1_40->u.Res.f0;
                      struct St *a2_10 = x1_40->u.Res.f1;
                      struct Res *r_103;
                      switch (a2_10->tag) {
                      case 0: {
                        int64_t a0_43 = a2_10->u.St.f0;
                        struct Heap *a1_19 = a2_10->u.St.f1;
                        struct Cell *c_104 = malloc(sizeof(struct Cell));
                        c_104->tag = 1;
                        c_104->u.Done.f0 = a3_23;
                        struct St *c_105 = malloc(sizeof(struct St));
                        c_105->tag = 0;
                        c_105->u.St.f0 = a0_43;
                        c_105->u.St.f1 = x_1(a1_19, a0_29, c_104);
                        r_103 = j_6(a3_23, c_105);
                        break;
                      }
                      default:
                        abort();
                      }
                      r_102 = r_103;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_101 = r_102;
                    break;
                  }
                  default:
                    abort();
                  }
                  r_100 = r_101;
                  break;
                }
                default:
                  abort();
                }
                r_71 = r_100;
                break;
              }
              default: {
                fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
                abort();
                r_71 = 0;
                break;
              }
              }
              r_17 = r_71;
              break;
            }
            default:
              abort();
            }
            r_16 = r_17;
            break;
          }
          case 1: {
            struct Res *r_106;
            switch (xs->tag) {
            case 1: {
              int64_t a0_45 = xs->u.ICons.f0;
              struct Ints *a1_20 = xs->u.ICons.f1;
              struct Res *r_107;
              switch (st->tag) {
              case 0: {
                int64_t a0_47 = st->u.St.f0;
                struct Heap *a1_21 = st->u.St.f1;
                struct RV *c_108 = malloc(sizeof(struct RV));
                c_108->tag = 0;
                c_108->u.RInt.f0 = 1;
                struct Cell *c_109 = malloc(sizeof(struct Cell));
                c_109->tag = 1;
                c_109->u.Done.f0 = c_108;
                struct St *c_110 = malloc(sizeof(struct St));
                c_110->tag = 0;
                c_110->u.St.f0 = (a0_47 + 1);
                c_110->u.St.f1 = x_1(a1_21, a0_47, c_109);
                struct St *s1_4 = c_110;
                struct Res *r_111;
                switch (s1_4->tag) {
                case 0: {
                  int64_t a0_49 = s1_4->u.St.f0;
                  struct Heap *a1_22 = s1_4->u.St.f1;
                  struct Ints *c_112 = malloc(sizeof(struct Ints));
                  c_112->tag = 0;
                  struct Ints *c_113 = malloc(sizeof(struct Ints));
                  c_113->tag = 1;
                  c_113->u.ICons.f0 = a0_45;
                  c_113->u.ICons.f1 = c_112;
                  struct Cell *c_114 = malloc(sizeof(struct Cell));
                  c_114->tag = 0;
                  c_114->u.Thunk.f0 = 5;
                  c_114->u.Thunk.f1 = c_113;
                  struct St *c_115 = malloc(sizeof(struct St));
                  c_115->tag = 0;
                  c_115->u.St.f0 = (a0_49 + 1);
                  c_115->u.St.f1 = x_1(a1_22, a0_49, c_114);
                  struct St *s1_5 = c_115;
                  struct RV *c_116 = malloc(sizeof(struct RV));
                  c_116->tag = 2;
                  c_116->u.RCons.f0 = a0_47;
                  c_116->u.RCons.f1 = a0_49;
                  struct RV *x_11 = c_116;
                  struct Res *c_117 = malloc(sizeof(struct Res));
                  c_117->tag = 0;
                  c_117->u.Res.f0 = x_11;
                  c_117->u.Res.f1 = s1_5;
                  r_111 = c_117;
                  break;
                }
                default:
                  abort();
                }
                r_107 = r_111;
                break;
              }
              default:
                abort();
              }
              r_106 = r_107;
              break;
            }
            default: {
              fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
              abort();
              r_106 = 0;
              break;
            }
            }
            r_16 = r_106;
            break;
          }
          default:
            abort();
          }
          r_15 = r_16;
          break;
        }
        case 1: {
          struct Res *r_118;
          switch (xs->tag) {
          case 1: {
            int64_t a0_51 = xs->u.ICons.f0;
            struct Ints *a1_23 = xs->u.ICons.f1;
            struct Res *r_122;
            switch (st->tag) {
            case 0: {
              int64_t a4_12 = st->u.St.f0;
              struct Heap *a4_13 = st->u.St.f1;
              struct Cell *x1_48 = x(a4_13, a0_51);
              struct Res *r_123;
              switch (x1_48->tag) {
              case 1: {
                struct RV *a0_54 = x1_48->u.Done.f0;
                r_123 = j_7(a0_54, st);
                break;
              }
              case 0: {
                int64_t x5_8 = x1_48->u.Thunk.f0;
                struct Ints *x6_6 = x1_48->u.Thunk.f1;
                struct Res *x1_49 = x_2(x5_8, x6_6, st);
                struct Res *r_124;
                switch (x1_49->tag) {
                case 0: {
                  struct RV *a3_27 = x1_49->u.Res.f0;
                  struct St *a2_12 = x1_49->u.Res.f1;
                  struct Res *r_125;
                  switch (a2_12->tag) {
                  case 0: {
                    int64_t a0_55 = a2_12->u.St.f0;
                    struct Heap *a1_24 = a2_12->u.St.f1;
                    struct Cell *c_126 = malloc(sizeof(struct Cell));
                    c_126->tag = 1;
                    c_126->u.Done.f0 = a3_27;
                    struct St *c_127 = malloc(sizeof(struct St));
                    c_127->tag = 0;
                    c_127->u.St.f0 = a0_55;
                    c_127->u.St.f1 = x_1(a1_24, a0_51, c_126);
                    r_125 = j_7(a3_27, c_127);
                    break;
                  }
                  default:
                    abort();
                  }
                  r_124 = r_125;
                  break;
                }
                default:
                  abort();
                }
                r_123 = r_124;
                break;
              }
              default:
                abort();
              }
              r_122 = r_123;
              break;
            }
            default:
              abort();
            }
            r_118 = r_122;
            break;
          }
          default: {
            fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
            abort();
            r_118 = 0;
            break;
          }
          }
          r_15 = r_118;
          break;
        }
        default:
          abort();
        }
        r_14 = r_15;
        break;
      }
      case 1: {
        struct Res *r_128;
        switch (xs->tag) {
        case 1: {
          int64_t a0_57 = xs->u.ICons.f0;
          struct Ints *a1_25 = xs->u.ICons.f1;
          int64_t x_13 = (a0_57 - 1);
          struct RV *c_129 = malloc(sizeof(struct RV));
          c_129->tag = 0;
          c_129->u.RInt.f0 = x_13;
          struct Res *c_130 = malloc(sizeof(struct Res));
          c_130->tag = 0;
          c_130->u.Res.f0 = c_129;
          c_130->u.Res.f1 = st;
          r_128 = c_130;
          break;
        }
        default: {
          fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
          abort();
          r_128 = 0;
          break;
        }
        }
        r_14 = r_128;
        break;
      }
      default:
        abort();
      }
      r_13 = r_14;
      break;
    }
    case 1: {
      struct Res *r_131;
      switch (xs->tag) {
      case 1: {
        int64_t a0_59 = xs->u.ICons.f0;
        struct Ints *a1_26 = xs->u.ICons.f1;
        int64_t x_14 = (a0_59 - 1);
        int64_t x_15 = (x_14 - 1);
        struct RV *c_132 = malloc(sizeof(struct RV));
        c_132->tag = 0;
        c_132->u.RInt.f0 = x_15;
        struct Res *c_133 = malloc(sizeof(struct Res));
        c_133->tag = 0;
        c_133->u.Res.f0 = c_132;
        c_133->u.Res.f1 = st;
        r_131 = c_133;
        break;
      }
      default: {
        fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
        abort();
        r_131 = 0;
        break;
      }
      }
      r_13 = r_131;
      break;
    }
    default:
      abort();
    }
    r_12 = r_13;
    break;
  }
  case 1: {
    struct Res *r_134;
    switch (xs->tag) {
    case 1: {
      int64_t a0_61 = xs->u.ICons.f0;
      struct Ints *a1_27 = xs->u.ICons.f1;
      struct Res *r_135;
      switch (st->tag) {
      case 0: {
        int64_t a0_63 = st->u.St.f0;
        struct Heap *a1_28 = st->u.St.f1;
        struct RV *c_136 = malloc(sizeof(struct RV));
        c_136->tag = 0;
        c_136->u.RInt.f0 = 0;
        struct Cell *c_137 = malloc(sizeof(struct Cell));
        c_137->tag = 1;
        c_137->u.Done.f0 = c_136;
        struct St *c_138 = malloc(sizeof(struct St));
        c_138->tag = 0;
        c_138->u.St.f0 = (a0_63 + 1);
        c_138->u.St.f1 = x_1(a1_28, a0_63, c_137);
        struct St *s1_6 = c_138;
        struct Res *r_139;
        switch (s1_6->tag) {
        case 0: {
          int64_t a0_65 = s1_6->u.St.f0;
          struct Heap *a1_29 = s1_6->u.St.f1;
          struct Ints *c_140 = malloc(sizeof(struct Ints));
          c_140->tag = 0;
          struct Ints *c_141 = malloc(sizeof(struct Ints));
          c_141->tag = 1;
          c_141->u.ICons.f0 = a0_61;
          c_141->u.ICons.f1 = c_140;
          struct Cell *c_142 = malloc(sizeof(struct Cell));
          c_142->tag = 0;
          c_142->u.Thunk.f0 = 4;
          c_142->u.Thunk.f1 = c_141;
          struct St *c_143 = malloc(sizeof(struct St));
          c_143->tag = 0;
          c_143->u.St.f0 = (a0_65 + 1);
          c_143->u.St.f1 = x_1(a1_29, a0_65, c_142);
          struct St *s1_7 = c_143;
          struct RV *c_144 = malloc(sizeof(struct RV));
          c_144->tag = 2;
          c_144->u.RCons.f0 = a0_63;
          c_144->u.RCons.f1 = a0_65;
          struct RV *x_16 = c_144;
          struct Res *c_145 = malloc(sizeof(struct Res));
          c_145->tag = 0;
          c_145->u.Res.f0 = x_16;
          c_145->u.Res.f1 = s1_7;
          r_139 = c_145;
          break;
        }
        default:
          abort();
        }
        r_135 = r_139;
        break;
      }
      default:
        abort();
      }
      r_134 = r_135;
      break;
    }
    default: {
      fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",356:34");
      abort();
      r_134 = 0;
      break;
    }
    }
    r_12 = r_134;
    break;
  }
  default:
    abort();
  }
  return r_12;
}
static struct Res *j_8(struct RV *v_9, struct St *s_9) {
  struct Res *c_157 = malloc(sizeof(struct Res));
  c_157->tag = 0;
  c_157->u.Res.f0 = v_9;
  c_157->u.Res.f1 = s_9;
  return c_157;
}
static struct Res *f(int64_t a_2, int64_t b, struct St *s_10);
static struct Res *j_9(struct RV *v_12, struct St *s_13) {
  struct Res *c_178 = malloc(sizeof(struct Res));
  c_178->tag = 0;
  c_178->u.Res.f0 = v_12;
  c_178->u.Res.f1 = s_13;
  return c_178;
}
static struct Res *j_10(int64_t b, int64_t a1_34, int64_t a0_75, struct RV *v_11, struct St *s_12) {
  struct Res *r_169;
  switch (v_11->tag) {
  case 0: {
    int64_t a0_77 = v_11->u.RInt.f0;
    struct Res *r_170;
    switch ((a0_77 == 0)) {
    case 0: {
      struct Res *r_171;
      switch (s_12->tag) {
      case 0: {
        int64_t a0_79 = s_12->u.St.f0;
        struct Heap *a1_35 = s_12->u.St.f1;
        struct Ints *c_172 = malloc(sizeof(struct Ints));
        c_172->tag = 0;
        struct Ints *c_173 = malloc(sizeof(struct Ints));
        c_173->tag = 1;
        c_173->u.ICons.f0 = b;
        c_173->u.ICons.f1 = c_172;
        struct Cell *c_174 = malloc(sizeof(struct Cell));
        c_174->tag = 0;
        c_174->u.Thunk.f0 = 3;
        c_174->u.Thunk.f1 = c_173;
        struct St *c_175 = malloc(sizeof(struct St));
        c_175->tag = 0;
        c_175->u.St.f0 = (a0_79 + 1);
        c_175->u.St.f1 = x_1(a1_35, a0_79, c_174);
        struct St *s1_11 = c_175;
        struct Res *x1_63 = f(a1_34, a0_79, s1_11);
        struct Res *r_176;
        switch (x1_63->tag) {
        case 0: {
          struct RV *a0_81 = x1_63->u.Res.f0;
          struct St *a1_36 = x1_63->u.Res.f1;
          struct Res *c_177 = malloc(sizeof(struct Res));
          c_177->tag = 0;
          c_177->u.Res.f0 = a0_81;
          c_177->u.Res.f1 = a1_36;
          r_176 = c_177;
          break;
        }
        default:
          abort();
        }
        r_171 = r_176;
        break;
      }
      default:
        abort();
      }
      r_170 = r_171;
      break;
    }
    case 1: {
      struct Res *r_179;
      switch (s_12->tag) {
      case 0: {
        int64_t a4_14 = s_12->u.St.f0;
        struct Heap *a4_15 = s_12->u.St.f1;
        struct Cell *x1_65 = x(a4_15, a0_75);
        struct Res *r_180;
        switch (x1_65->tag) {
        case 1: {
          struct RV *a0_82 = x1_65->u.Done.f0;
          r_180 = j_9(a0_82, s_12);
          break;
        }
        case 0: {
          int64_t x5_9 = x1_65->u.Thunk.f0;
          struct Ints *x6_7 = x1_65->u.Thunk.f1;
          struct Res *x1_66 = x_2(x5_9, x6_7, s_12);
          struct Res *r_181;
          switch (x1_66->tag) {
          case 0: {
            struct RV *a3_31 = x1_66->u.Res.f0;
            struct St *a2_14 = x1_66->u.Res.f1;
            struct Res *r_182;
            switch (a2_14->tag) {
            case 0: {
              int64_t a0_83 = a2_14->u.St.f0;
              struct Heap *a1_37 = a2_14->u.St.f1;
              struct Cell *c_183 = malloc(sizeof(struct Cell));
              c_183->tag = 1;
              c_183->u.Done.f0 = a3_31;
              struct St *c_184 = malloc(sizeof(struct St));
              c_184->tag = 0;
              c_184->u.St.f0 = a0_83;
              c_184->u.St.f1 = x_1(a1_37, a0_75, c_183);
              r_182 = j_9(a3_31, c_184);
              break;
            }
            default:
              abort();
            }
            r_181 = r_182;
            break;
          }
          default:
            abort();
          }
          r_180 = r_181;
          break;
        }
        default:
          abort();
        }
        r_179 = r_180;
        break;
      }
      default:
        abort();
      }
      r_170 = r_179;
      break;
    }
    default:
      abort();
    }
    r_169 = r_170;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",325:32");
    abort();
    r_169 = 0;
    break;
  }
  }
  return r_169;
}
static struct Res *j_11(int64_t b, struct RV *v_10, struct St *s_11) {
  struct Res *r_166;
  switch (v_10->tag) {
  case 1: {
    struct RV *c_167 = malloc(sizeof(struct RV));
    c_167->tag = 0;
    c_167->u.RInt.f0 = 0;
    struct Res *c_168 = malloc(sizeof(struct Res));
    c_168->tag = 0;
    c_168->u.Res.f0 = c_167;
    c_168->u.Res.f1 = s_11;
    r_166 = c_168;
    break;
  }
  case 2: {
    int64_t a0_75 = v_10->u.RCons.f0;
    int64_t a1_34 = v_10->u.RCons.f1;
    struct Res *r_185;
    switch (s_11->tag) {
    case 0: {
      int64_t a4_16 = s_11->u.St.f0;
      struct Heap *a4_17 = s_11->u.St.f1;
      struct Cell *x1_69 = x(a4_17, b);
      struct Res *r_186;
      switch (x1_69->tag) {
      case 1: {
        struct RV *a0_84 = x1_69->u.Done.f0;
        r_186 = j_10(b, a1_34, a0_75, a0_84, s_11);
        break;
      }
      case 0: {
        int64_t x5_10 = x1_69->u.Thunk.f0;
        struct Ints *x6_8 = x1_69->u.Thunk.f1;
        struct Res *x1_70 = x_2(x5_10, x6_8, s_11);
        struct Res *r_187;
        switch (x1_70->tag) {
        case 0: {
          struct RV *a3_35 = x1_70->u.Res.f0;
          struct St *a2_16 = x1_70->u.Res.f1;
          struct Res *r_188;
          switch (a2_16->tag) {
          case 0: {
            int64_t a0_85 = a2_16->u.St.f0;
            struct Heap *a1_38 = a2_16->u.St.f1;
            struct Cell *c_189 = malloc(sizeof(struct Cell));
            c_189->tag = 1;
            c_189->u.Done.f0 = a3_35;
            struct St *c_190 = malloc(sizeof(struct St));
            c_190->tag = 0;
            c_190->u.St.f0 = a0_85;
            c_190->u.St.f1 = x_1(a1_38, b, c_189);
            r_188 = j_10(b, a1_34, a0_75, a3_35, c_190);
            break;
          }
          default:
            abort();
          }
          r_187 = r_188;
          break;
        }
        default:
          abort();
        }
        r_186 = r_187;
        break;
      }
      default:
        abort();
      }
      r_185 = r_186;
      break;
    }
    default:
      abort();
    }
    r_166 = r_185;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_166 = 0;
    break;
  }
  }
  return r_166;
}
static struct Res *f(int64_t a_2, int64_t b, struct St *s_10) {
  struct Res *r_191;
  switch (s_10->tag) {
  case 0: {
    int64_t a4_18 = s_10->u.St.f0;
    struct Heap *a4_19 = s_10->u.St.f1;
    struct Cell *x1_73 = x(a4_19, a_2);
    struct Res *r_192;
    switch (x1_73->tag) {
    case 1: {
      struct RV *a0_86 = x1_73->u.Done.f0;
      r_192 = j_11(b, a0_86, s_10);
      break;
    }
    case 0: {
      int64_t x5_11 = x1_73->u.Thunk.f0;
      struct Ints *x6_9 = x1_73->u.Thunk.f1;
      struct Res *x1_74 = x_2(x5_11, x6_9, s_10);
      struct Res *r_193;
      switch (x1_74->tag) {
      case 0: {
        struct RV *a3_39 = x1_74->u.Res.f0;
        struct St *a2_18 = x1_74->u.Res.f1;
        struct Res *r_194;
        switch (a2_18->tag) {
        case 0: {
          int64_t a0_87 = a2_18->u.St.f0;
          struct Heap *a1_39 = a2_18->u.St.f1;
          struct Cell *c_195 = malloc(sizeof(struct Cell));
          c_195->tag = 1;
          c_195->u.Done.f0 = a3_39;
          struct St *c_196 = malloc(sizeof(struct St));
          c_196->tag = 0;
          c_196->u.St.f0 = a0_87;
          c_196->u.St.f1 = x_1(a1_39, a_2, c_195);
          r_194 = j_11(b, a3_39, c_196);
          break;
        }
        default:
          abort();
        }
        r_193 = r_194;
        break;
      }
      default:
        abort();
      }
      r_192 = r_193;
      break;
    }
    default:
      abort();
    }
    r_191 = r_192;
    break;
  }
  default:
    abort();
  }
  return r_191;
}
static struct Res *j_12(struct RV *v_13, struct St *s_14) { return j_8(v_13, s_14); }
static struct Res *j_13(int64_t n, struct RV *v_8, struct St *s_8) {
  struct Res *r_158;
  switch (v_8->tag) {
  case 1: {
    struct RV *c_159 = malloc(sizeof(struct RV));
    c_159->tag = 0;
    c_159->u.RInt.f0 = 0;
    r_158 = j_8(c_159, s_8);
    break;
  }
  case 2: {
    int64_t a0_71 = v_8->u.RCons.f0;
    int64_t a1_32 = v_8->u.RCons.f1;
    struct Res *r_160;
    switch ((n == 0)) {
    case 0: {
      struct Res *r_161;
      switch (s_8->tag) {
      case 0: {
        int64_t a0_73 = s_8->u.St.f0;
        struct Heap *a1_33 = s_8->u.St.f1;
        struct Ints *c_162 = malloc(sizeof(struct Ints));
        c_162->tag = 0;
        struct Ints *c_163 = malloc(sizeof(struct Ints));
        c_163->tag = 1;
        c_163->u.ICons.f0 = n;
        c_163->u.ICons.f1 = c_162;
        struct Cell *c_164 = malloc(sizeof(struct Cell));
        c_164->tag = 0;
        c_164->u.Thunk.f0 = 2;
        c_164->u.Thunk.f1 = c_163;
        struct St *c_165 = malloc(sizeof(struct St));
        c_165->tag = 0;
        c_165->u.St.f0 = (a0_73 + 1);
        c_165->u.St.f1 = x_1(a1_33, a0_73, c_164);
        struct St *s1_10 = c_165;
        struct Res *x1_76 = f(a1_32, a0_73, s1_10);
        struct Res *r_197;
        switch (x1_76->tag) {
        case 0: {
          struct RV *a0_89 = x1_76->u.Res.f0;
          struct St *a1_40 = x1_76->u.Res.f1;
          r_197 = j_8(a0_89, a1_40);
          break;
        }
        default:
          abort();
        }
        r_161 = r_197;
        break;
      }
      default:
        abort();
      }
      r_160 = r_161;
      break;
    }
    case 1: {
      struct Res *r_198;
      switch (s_8->tag) {
      case 0: {
        int64_t a4_20 = s_8->u.St.f0;
        struct Heap *a4_21 = s_8->u.St.f1;
        struct Cell *x1_78 = x(a4_21, a0_71);
        struct Res *r_199;
        switch (x1_78->tag) {
        case 1: {
          struct RV *a0_90 = x1_78->u.Done.f0;
          r_199 = j_12(a0_90, s_8);
          break;
        }
        case 0: {
          int64_t x5_12 = x1_78->u.Thunk.f0;
          struct Ints *x6_10 = x1_78->u.Thunk.f1;
          struct Res *x1_79 = x_2(x5_12, x6_10, s_8);
          struct Res *r_200;
          switch (x1_79->tag) {
          case 0: {
            struct RV *a3_43 = x1_79->u.Res.f0;
            struct St *a2_20 = x1_79->u.Res.f1;
            struct Res *r_201;
            switch (a2_20->tag) {
            case 0: {
              int64_t a0_91 = a2_20->u.St.f0;
              struct Heap *a1_41 = a2_20->u.St.f1;
              struct Cell *c_202 = malloc(sizeof(struct Cell));
              c_202->tag = 1;
              c_202->u.Done.f0 = a3_43;
              struct St *c_203 = malloc(sizeof(struct St));
              c_203->tag = 0;
              c_203->u.St.f0 = a0_91;
              c_203->u.St.f1 = x_1(a1_41, a0_71, c_202);
              r_201 = j_12(a3_43, c_203);
              break;
            }
            default:
              abort();
            }
            r_200 = r_201;
            break;
          }
          default:
            abort();
          }
          r_199 = r_200;
          break;
        }
        default:
          abort();
        }
        r_198 = r_199;
        break;
      }
      default:
        abort();
      }
      r_160 = r_198;
      break;
    }
    default:
      abort();
    }
    r_158 = r_160;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",324:33");
    abort();
    r_158 = 0;
    break;
  }
  }
  return r_158;
}

int64_t pfibs(int64_t n) {
  struct Heap *c_146 = malloc(sizeof(struct Heap));
  c_146->tag = 0;
  struct St *c_147 = malloc(sizeof(struct St));
  c_147->tag = 0;
  c_147->u.St.f0 = 1;
  c_147->u.St.f1 = c_146;
  struct St *x1_56 = c_147;
  struct Res *r_148;
  switch (x1_56->tag) {
  case 0: {
    int64_t a0_67 = x1_56->u.St.f0;
    struct Heap *a1_30 = x1_56->u.St.f1;
    struct RV *c_149 = malloc(sizeof(struct RV));
    c_149->tag = 1;
    struct Cell *c_150 = malloc(sizeof(struct Cell));
    c_150->tag = 1;
    c_150->u.Done.f0 = c_149;
    struct St *c_151 = malloc(sizeof(struct St));
    c_151->tag = 0;
    c_151->u.St.f0 = (a0_67 + 1);
    c_151->u.St.f1 = x_1(a1_30, a0_67, c_150);
    struct St *s1_8 = c_151;
    struct Res *r_152;
    switch (s1_8->tag) {
    case 0: {
      int64_t a0_69 = s1_8->u.St.f0;
      struct Heap *a1_31 = s1_8->u.St.f1;
      struct Ints *c_153 = malloc(sizeof(struct Ints));
      c_153->tag = 0;
      struct Ints *c_154 = malloc(sizeof(struct Ints));
      c_154->tag = 1;
      c_154->u.ICons.f0 = a0_67;
      c_154->u.ICons.f1 = c_153;
      struct Cell *c_155 = malloc(sizeof(struct Cell));
      c_155->tag = 0;
      c_155->u.Thunk.f0 = 0;
      c_155->u.Thunk.f1 = c_154;
      struct St *c_156 = malloc(sizeof(struct St));
      c_156->tag = 0;
      c_156->u.St.f0 = a0_69;
      c_156->u.St.f1 = x_1(a1_31, a0_67, c_155);
      struct St *s1_9 = c_156;
      struct Res *r_204;
      switch (s1_9->tag) {
      case 0: {
        int64_t a4_22 = s1_9->u.St.f0;
        struct Heap *a4_23 = s1_9->u.St.f1;
        struct Cell *x1_82 = x(a4_23, a0_67);
        struct Res *r_205;
        switch (x1_82->tag) {
        case 1: {
          struct RV *a0_92 = x1_82->u.Done.f0;
          r_205 = j_13(n, a0_92, s1_9);
          break;
        }
        case 0: {
          int64_t x5_13 = x1_82->u.Thunk.f0;
          struct Ints *x6_11 = x1_82->u.Thunk.f1;
          struct Res *x1_83 = x_2(x5_13, x6_11, s1_9);
          struct Res *r_206;
          switch (x1_83->tag) {
          case 0: {
            struct RV *a3_47 = x1_83->u.Res.f0;
            struct St *a2_22 = x1_83->u.Res.f1;
            struct Res *r_207;
            switch (a2_22->tag) {
            case 0: {
              int64_t a0_93 = a2_22->u.St.f0;
              struct Heap *a1_42 = a2_22->u.St.f1;
              struct Cell *c_208 = malloc(sizeof(struct Cell));
              c_208->tag = 1;
              c_208->u.Done.f0 = a3_47;
              struct St *c_209 = malloc(sizeof(struct St));
              c_209->tag = 0;
              c_209->u.St.f0 = a0_93;
              c_209->u.St.f1 = x_1(a1_42, a0_67, c_208);
              r_207 = j_13(n, a3_47, c_209);
              break;
            }
            default:
              abort();
            }
            r_206 = r_207;
            break;
          }
          default:
            abort();
          }
          r_205 = r_206;
          break;
        }
        default:
          abort();
        }
        r_204 = r_205;
        break;
      }
      default:
        abort();
      }
      r_152 = r_204;
      break;
    }
    default:
      abort();
    }
    r_148 = r_152;
    break;
  }
  default:
    abort();
  }
  struct Res *x1_85 = r_148;
  int64_t r_210;
  switch (x1_85->tag) {
  case 0: {
    struct RV *x3_2 = x1_85->u.Res.f0;
    struct St *x4_2 = x1_85->u.Res.f1;
    int64_t r_211;
    switch (x3_2->tag) {
    case 0: {
      int64_t a0_94 = x3_2->u.RInt.f0;
      r_211 = a0_94;
      break;
    }
    default: {
      fprintf(stderr, "%s\n", "\"./LowFutamuraLazy.hs\",763:39");
      abort();
      r_211 = 0;
      break;
    }
    }
    r_210 = r_211;
    break;
  }
  default:
    abort();
  }
  return r_210;
}
