/* Generated by tests/LowFutamura.hs (see LowFutamura.ref), formatted with clang-format:
 *
 *   pfactorial :: Low Res
 *   pfactorial = eval (deBruijn factorial)
 *
 * the call by need lambda calculus interpreter of LowLambda.hs, staged, applied
 * to the factorial program (the Y combinator applied to \ fact n -> ...).
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

struct Cell {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Env *f1;
    } Thunk;
    struct {
      struct Val *f0;
    } Done;
  } u;
};
struct Env {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Env *f1;
    } Bind;
  } u;
};
struct Val {
  int tag;
  union {
    struct {
      int64_t f0;
    } VInt;
    struct {
      struct Env *f0;
      int64_t f1;
    } VClo;
  } u;
};
struct Heap {
  int tag;
  union {
    struct {
      struct Heap *f0;
      struct Cell *f1;
      struct Heap *f2;
    } Node;
  } u;
};
/* Data.Bool_Type.Bool: False=0, True=1 */
struct Res {
  int tag;
  union {
    struct {
      struct Val *f0;
      struct St *f1;
    } Res;
  } u;
};
struct St {
  int tag;
  union {
    struct {
      int64_t f0;
      struct Heap *f1;
      int64_t f2;
    } St;
  } u;
};

static struct Cell *x(struct Heap *h, int64_t a);
static struct Cell *x(struct Heap *h, int64_t a) {
  struct Cell *r_0;
  switch (h->tag) {
  case 1: {
    struct Heap *x3 = h->u.Node.f0;
    struct Cell *x4 = h->u.Node.f1;
    struct Heap *x5 = h->u.Node.f2;
    struct Cell *r_1;
    switch ((a == 1)) {
    case 0: {
      struct Cell *r_2;
      switch (((a - (2 * (a / 2))) == 0)) {
      case 0: {
        r_2 = x(x5, (a / 2));
        break;
      }
      case 1: {
        r_2 = x(x3, (a / 2));
        break;
      }
      default:
        abort();
      }
      r_1 = r_2;
      break;
    }
    case 1: {
      r_1 = x4;
      break;
    }
    default:
      abort();
    }
    r_0 = r_1;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",164:21");
    abort();
    r_0 = 0;
    break;
  }
  }
  return r_0;
}
static struct Heap *x_1(struct Heap *h_1, int64_t a_1, struct Cell *c);
static struct Heap *x_1(struct Heap *h_1, int64_t a_1, struct Cell *c) {
  struct Heap *r_3;
  switch (h_1->tag) {
  case 0: {
    struct Heap *c_4 = malloc(sizeof(struct Heap));
    c_4->tag = 0;
    struct Heap *c_5 = malloc(sizeof(struct Heap));
    c_5->tag = 0;
    struct Heap *c_6 = malloc(sizeof(struct Heap));
    c_6->tag = 1;
    c_6->u.Node.f0 = c_4;
    c_6->u.Node.f1 = c;
    c_6->u.Node.f2 = c_5;
    r_3 = c_6;
    break;
  }
  case 1: {
    struct Heap *x3_1 = h_1->u.Node.f0;
    struct Cell *x4_1 = h_1->u.Node.f1;
    struct Heap *x5_1 = h_1->u.Node.f2;
    struct Heap *r_7;
    switch ((a_1 == 1)) {
    case 0: {
      struct Heap *r_8;
      switch (((a_1 - (2 * (a_1 / 2))) == 0)) {
      case 0: {
        struct Heap *c_9 = malloc(sizeof(struct Heap));
        c_9->tag = 1;
        c_9->u.Node.f0 = x3_1;
        c_9->u.Node.f1 = x4_1;
        c_9->u.Node.f2 = x_1(x5_1, (a_1 / 2), c);
        r_8 = c_9;
        break;
      }
      case 1: {
        struct Heap *c_10 = malloc(sizeof(struct Heap));
        c_10->tag = 1;
        c_10->u.Node.f0 = x_1(x3_1, (a_1 / 2), c);
        c_10->u.Node.f1 = x4_1;
        c_10->u.Node.f2 = x5_1;
        r_8 = c_10;
        break;
      }
      default:
        abort();
      }
      r_7 = r_8;
      break;
    }
    case 1: {
      struct Heap *c_11 = malloc(sizeof(struct Heap));
      c_11->tag = 1;
      c_11->u.Node.f0 = x3_1;
      c_11->u.Node.f1 = c;
      c_11->u.Node.f2 = x5_1;
      r_7 = c_11;
      break;
    }
    default:
      abort();
    }
    r_3 = r_7;
    break;
  }
  default:
    abort();
  }
  return r_3;
}
static int64_t x_2(struct Env *env, int64_t n);
static int64_t x_2(struct Env *env, int64_t n) {
  int64_t r_12;
  switch (env->tag) {
  case 1: {
    int64_t x3_2 = env->u.Bind.f0;
    struct Env *x4_2 = env->u.Bind.f1;
    int64_t r_13;
    switch ((n == 0)) {
    case 0: {
      r_13 = x_2(x4_2, (n - 1));
      break;
    }
    case 1: {
      r_13 = x3_2;
      break;
    }
    default:
      abort();
    }
    r_12 = r_13;
    break;
  }
  default: {
    fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",175:21");
    abort();
    r_12 = 0;
    break;
  }
  }
  return r_12;
}
static struct Res *x_3(int64_t l, struct Env *env_1, struct St *st);
static struct Res *x_3(int64_t l, struct Env *env_1, struct St *st) {
  struct Res *r_14;
  switch ((l == 0)) {
  case 0: {
    struct Res *r_15;
    switch ((l == 1)) {
    case 0: {
      struct Res *r_16;
      switch ((l == 2)) {
      case 0: {
        struct Res *r_17;
        switch ((l == 3)) {
        case 0: {
          struct Res *r_18;
          switch ((l == 4)) {
          case 0: {
            struct Res *r_19;
            switch ((l == 5)) {
            case 0: {
              struct Res *r_20;
              switch ((l == 6)) {
              case 0: {
                struct Res *r_21;
                switch ((l == 7)) {
                case 0: {
                  struct Res *r_22;
                  switch ((l == 8)) {
                  case 0: {
                    struct Res *r_23;
                    switch ((l == 9)) {
                    case 0: {
                      struct Res *r_24;
                      switch ((l == 10)) {
                      case 0: {
                        struct Res *r_25;
                        switch (st->tag) {
                        case 0: {
                          int64_t x3_3 = st->u.St.f0;
                          struct Heap *x4_3 = st->u.St.f1;
                          int64_t x5_2 = st->u.St.f2;
                          struct St *c_26 = malloc(sizeof(struct St));
                          c_26->tag = 0;
                          c_26->u.St.f0 = x3_3;
                          c_26->u.St.f1 = x4_3;
                          c_26->u.St.f2 = (x5_2 + 1);
                          struct St *st0 = c_26;
                          struct Res *r_27;
                          switch (st0->tag) {
                          case 0: {
                            int64_t x3_4 = st0->u.St.f0;
                            struct Heap *x4_4 = st0->u.St.f1;
                            int64_t x5_3 = st0->u.St.f2;
                            struct St *c_28 = malloc(sizeof(struct St));
                            c_28->tag = 0;
                            c_28->u.St.f0 = x3_4;
                            c_28->u.St.f1 = x4_4;
                            c_28->u.St.f2 = (x5_3 + 1);
                            struct St *st0_1 = c_28;
                            int64_t a_2 = x_2(env_1, 0);
                            struct Cell *x1_5 = x(x4_4, a_2);
                            struct Res *r_29;
                            switch (x1_5->tag) {
                            case 1: {
                              struct Val *a0 = x1_5->u.Done.f0;
                              struct Res *c_30 = malloc(sizeof(struct Res));
                              c_30->tag = 0;
                              c_30->u.Res.f0 = a0;
                              c_30->u.Res.f1 = st0_1;
                              r_29 = c_30;
                              break;
                            }
                            case 0: {
                              int64_t a6 = x1_5->u.Thunk.f0;
                              struct Env *x6 = x1_5->u.Thunk.f1;
                              struct Res *x1_6 = x_3(a6, x6, st0_1);
                              struct Res *r_31;
                              switch (x1_6->tag) {
                              case 0: {
                                struct Val *a4 = x1_6->u.Res.f0;
                                struct St *a5 = x1_6->u.Res.f1;
                                struct Res *r_32;
                                switch (a5->tag) {
                                case 0: {
                                  int64_t a0_1 = a5->u.St.f0;
                                  struct Heap *a1 = a5->u.St.f1;
                                  int64_t a2 = a5->u.St.f2;
                                  struct Cell *c_33 = malloc(sizeof(struct Cell));
                                  c_33->tag = 1;
                                  c_33->u.Done.f0 = a4;
                                  struct St *c_34 = malloc(sizeof(struct St));
                                  c_34->tag = 0;
                                  c_34->u.St.f0 = a0_1;
                                  c_34->u.St.f1 = x_1(a1, a_2, c_33);
                                  c_34->u.St.f2 = a2;
                                  struct Res *c_35 = malloc(sizeof(struct Res));
                                  c_35->tag = 0;
                                  c_35->u.Res.f0 = a4;
                                  c_35->u.Res.f1 = c_34;
                                  r_32 = c_35;
                                  break;
                                }
                                default:
                                  abort();
                                }
                                r_31 = r_32;
                                break;
                              }
                              default:
                                abort();
                              }
                              r_29 = r_31;
                              break;
                            }
                            default:
                              abort();
                            }
                            r_27 = r_29;
                            break;
                          }
                          default:
                            abort();
                          }
                          struct Res *x1_8 = r_27;
                          struct Res *r_36;
                          switch (x1_8->tag) {
                          case 0: {
                            struct Val *a5_1 = x1_8->u.Res.f0;
                            struct St *a6_1 = x1_8->u.Res.f1;
                            struct Res *r_37;
                            switch (a5_1->tag) {
                            case 0: {
                              int64_t a2_1 = a5_1->u.VInt.f0;
                              struct Res *r_38;
                              switch (a6_1->tag) {
                              case 0: {
                                int64_t x3_5 = a6_1->u.St.f0;
                                struct Heap *x4_5 = a6_1->u.St.f1;
                                int64_t x5_4 = a6_1->u.St.f2;
                                struct St *c_39 = malloc(sizeof(struct St));
                                c_39->tag = 0;
                                c_39->u.St.f0 = x3_5;
                                c_39->u.St.f1 = x4_5;
                                c_39->u.St.f2 = (x5_4 + 1);
                                struct St *st0_2 = c_39;
                                struct Val *c_40 = malloc(sizeof(struct Val));
                                c_40->tag = 0;
                                c_40->u.VInt.f0 = 1;
                                struct Res *c_41 = malloc(sizeof(struct Res));
                                c_41->tag = 0;
                                c_41->u.Res.f0 = c_40;
                                c_41->u.Res.f1 = st0_2;
                                r_38 = c_41;
                                break;
                              }
                              default:
                                abort();
                              }
                              struct Res *x1_11 = r_38;
                              struct Res *r_42;
                              switch (x1_11->tag) {
                              case 0: {
                                struct Val *a1_1 = x1_11->u.Res.f0;
                                struct St *a3_3 = x1_11->u.Res.f1;
                                struct Res *r_43;
                                switch (a1_1->tag) {
                                case 0: {
                                  int64_t a0_2 = a1_1->u.VInt.f0;
                                  struct Val *c_44 = malloc(sizeof(struct Val));
                                  c_44->tag = 0;
                                  c_44->u.VInt.f0 = (a2_1 - a0_2);
                                  struct Res *c_45 = malloc(sizeof(struct Res));
                                  c_45->tag = 0;
                                  c_45->u.Res.f0 = c_44;
                                  c_45->u.Res.f1 = a3_3;
                                  r_43 = c_45;
                                  break;
                                }
                                default: {
                                  fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",133:36");
                                  abort();
                                  r_43 = 0;
                                  break;
                                }
                                }
                                r_42 = r_43;
                                break;
                              }
                              default:
                                abort();
                              }
                              r_37 = r_42;
                              break;
                            }
                            default: {
                              fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",129:28");
                              abort();
                              r_37 = 0;
                              break;
                            }
                            }
                            r_36 = r_37;
                            break;
                          }
                          default:
                            abort();
                          }
                          r_25 = r_36;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_24 = r_25;
                        break;
                      }
                      case 1: {
                        struct Res *r_46;
                        switch (st->tag) {
                        case 0: {
                          int64_t x3_6 = st->u.St.f0;
                          struct Heap *x4_6 = st->u.St.f1;
                          int64_t x5_5 = st->u.St.f2;
                          struct St *c_47 = malloc(sizeof(struct St));
                          c_47->tag = 0;
                          c_47->u.St.f0 = x3_6;
                          c_47->u.St.f1 = x4_6;
                          c_47->u.St.f2 = (x5_5 + 1);
                          struct St *st0_3 = c_47;
                          struct Res *r_48;
                          switch (st0_3->tag) {
                          case 0: {
                            int64_t x3_7 = st0_3->u.St.f0;
                            struct Heap *x4_7 = st0_3->u.St.f1;
                            int64_t x5_6 = st0_3->u.St.f2;
                            struct St *c_49 = malloc(sizeof(struct St));
                            c_49->tag = 0;
                            c_49->u.St.f0 = x3_7;
                            c_49->u.St.f1 = x4_7;
                            c_49->u.St.f2 = (x5_6 + 1);
                            struct St *st0_4 = c_49;
                            int64_t a_3 = x_2(env_1, 0);
                            struct Cell *x1_15 = x(x4_7, a_3);
                            struct Res *r_50;
                            switch (x1_15->tag) {
                            case 1: {
                              struct Val *a0_3 = x1_15->u.Done.f0;
                              struct Res *c_51 = malloc(sizeof(struct Res));
                              c_51->tag = 0;
                              c_51->u.Res.f0 = a0_3;
                              c_51->u.Res.f1 = st0_4;
                              r_50 = c_51;
                              break;
                            }
                            case 0: {
                              int64_t a6_2 = x1_15->u.Thunk.f0;
                              struct Env *x6_1 = x1_15->u.Thunk.f1;
                              struct Res *x1_16 = x_3(a6_2, x6_1, st0_4);
                              struct Res *r_52;
                              switch (x1_16->tag) {
                              case 0: {
                                struct Val *a4_4 = x1_16->u.Res.f0;
                                struct St *a5_2 = x1_16->u.Res.f1;
                                struct Res *r_53;
                                switch (a5_2->tag) {
                                case 0: {
                                  int64_t a0_4 = a5_2->u.St.f0;
                                  struct Heap *a1_3 = a5_2->u.St.f1;
                                  int64_t a2_2 = a5_2->u.St.f2;
                                  struct Cell *c_54 = malloc(sizeof(struct Cell));
                                  c_54->tag = 1;
                                  c_54->u.Done.f0 = a4_4;
                                  struct St *c_55 = malloc(sizeof(struct St));
                                  c_55->tag = 0;
                                  c_55->u.St.f0 = a0_4;
                                  c_55->u.St.f1 = x_1(a1_3, a_3, c_54);
                                  c_55->u.St.f2 = a2_2;
                                  struct Res *c_56 = malloc(sizeof(struct Res));
                                  c_56->tag = 0;
                                  c_56->u.Res.f0 = a4_4;
                                  c_56->u.Res.f1 = c_55;
                                  r_53 = c_56;
                                  break;
                                }
                                default:
                                  abort();
                                }
                                r_52 = r_53;
                                break;
                              }
                              default:
                                abort();
                              }
                              r_50 = r_52;
                              break;
                            }
                            default:
                              abort();
                            }
                            r_48 = r_50;
                            break;
                          }
                          default:
                            abort();
                          }
                          struct Res *x1_18 = r_48;
                          struct Res *r_57;
                          switch (x1_18->tag) {
                          case 0: {
                            struct Val *a2_3 = x1_18->u.Res.f0;
                            struct St *a3_7 = x1_18->u.Res.f1;
                            struct Res *r_58;
                            switch (a2_3->tag) {
                            case 0: {
                              int64_t a0_5 = a2_3->u.VInt.f0;
                              struct Res *r_59;
                              switch ((a0_5 == 0)) {
                              case 0: {
                                struct Res *r_60;
                                switch (a3_7->tag) {
                                case 0: {
                                  int64_t x3_8 = a3_7->u.St.f0;
                                  struct Heap *x4_8 = a3_7->u.St.f1;
                                  int64_t x5_7 = a3_7->u.St.f2;
                                  struct St *c_61 = malloc(sizeof(struct St));
                                  c_61->tag = 0;
                                  c_61->u.St.f0 = x3_8;
                                  c_61->u.St.f1 = x4_8;
                                  c_61->u.St.f2 = (x5_7 + 1);
                                  struct St *st0_5 = c_61;
                                  struct Res *r_62;
                                  switch (st0_5->tag) {
                                  case 0: {
                                    int64_t x3_9 = st0_5->u.St.f0;
                                    struct Heap *x4_9 = st0_5->u.St.f1;
                                    int64_t x5_8 = st0_5->u.St.f2;
                                    struct St *c_63 = malloc(sizeof(struct St));
                                    c_63->tag = 0;
                                    c_63->u.St.f0 = x3_9;
                                    c_63->u.St.f1 = x4_9;
                                    c_63->u.St.f2 = (x5_8 + 1);
                                    struct St *st0_6 = c_63;
                                    int64_t a_4 = x_2(env_1, 0);
                                    struct Cell *x1_22 = x(x4_9, a_4);
                                    struct Res *r_64;
                                    switch (x1_22->tag) {
                                    case 1: {
                                      struct Val *a0_6 = x1_22->u.Done.f0;
                                      struct Res *c_65 = malloc(sizeof(struct Res));
                                      c_65->tag = 0;
                                      c_65->u.Res.f0 = a0_6;
                                      c_65->u.Res.f1 = st0_6;
                                      r_64 = c_65;
                                      break;
                                    }
                                    case 0: {
                                      int64_t a6_3 = x1_22->u.Thunk.f0;
                                      struct Env *x6_2 = x1_22->u.Thunk.f1;
                                      struct Res *x1_23 = x_3(a6_3, x6_2, st0_6);
                                      struct Res *r_66;
                                      switch (x1_23->tag) {
                                      case 0: {
                                        struct Val *a4_5 = x1_23->u.Res.f0;
                                        struct St *a5_3 = x1_23->u.Res.f1;
                                        struct Res *r_67;
                                        switch (a5_3->tag) {
                                        case 0: {
                                          int64_t a0_7 = a5_3->u.St.f0;
                                          struct Heap *a1_6 = a5_3->u.St.f1;
                                          int64_t a2_4 = a5_3->u.St.f2;
                                          struct Cell *c_68 = malloc(sizeof(struct Cell));
                                          c_68->tag = 1;
                                          c_68->u.Done.f0 = a4_5;
                                          struct St *c_69 = malloc(sizeof(struct St));
                                          c_69->tag = 0;
                                          c_69->u.St.f0 = a0_7;
                                          c_69->u.St.f1 = x_1(a1_6, a_4, c_68);
                                          c_69->u.St.f2 = a2_4;
                                          struct Res *c_70 = malloc(sizeof(struct Res));
                                          c_70->tag = 0;
                                          c_70->u.Res.f0 = a4_5;
                                          c_70->u.Res.f1 = c_69;
                                          r_67 = c_70;
                                          break;
                                        }
                                        default:
                                          abort();
                                        }
                                        r_66 = r_67;
                                        break;
                                      }
                                      default:
                                        abort();
                                      }
                                      r_64 = r_66;
                                      break;
                                    }
                                    default:
                                      abort();
                                    }
                                    r_62 = r_64;
                                    break;
                                  }
                                  default:
                                    abort();
                                  }
                                  struct Res *x1_25 = r_62;
                                  struct Res *r_71;
                                  switch (x1_25->tag) {
                                  case 0: {
                                    struct Val *a5_4 = x1_25->u.Res.f0;
                                    struct St *a6_4 = x1_25->u.Res.f1;
                                    struct Res *r_72;
                                    switch (a5_4->tag) {
                                    case 0: {
                                      int64_t a2_5 = a5_4->u.VInt.f0;
                                      struct Res *r_73;
                                      switch (a6_4->tag) {
                                      case 0: {
                                        int64_t x3_10 = a6_4->u.St.f0;
                                        struct Heap *x4_10 = a6_4->u.St.f1;
                                        int64_t x5_9 = a6_4->u.St.f2;
                                        struct St *c_74 = malloc(sizeof(struct St));
                                        c_74->tag = 0;
                                        c_74->u.St.f0 = x3_10;
                                        c_74->u.St.f1 = x4_10;
                                        c_74->u.St.f2 = (x5_9 + 1);
                                        struct St *st0_7 = c_74;
                                        struct Res *r_75;
                                        switch (st0_7->tag) {
                                        case 0: {
                                          int64_t x3_11 = st0_7->u.St.f0;
                                          struct Heap *x4_11 = st0_7->u.St.f1;
                                          int64_t x5_10 = st0_7->u.St.f2;
                                          struct St *c_76 = malloc(sizeof(struct St));
                                          c_76->tag = 0;
                                          c_76->u.St.f0 = x3_11;
                                          c_76->u.St.f1 = x4_11;
                                          c_76->u.St.f2 = (x5_10 + 1);
                                          struct St *st0_8 = c_76;
                                          int64_t a_5 = x_2(env_1, 1);
                                          struct Cell *x1_29 = x(x4_11, a_5);
                                          struct Res *r_77;
                                          switch (x1_29->tag) {
                                          case 1: {
                                            struct Val *a0_8 = x1_29->u.Done.f0;
                                            struct Res *c_78 = malloc(sizeof(struct Res));
                                            c_78->tag = 0;
                                            c_78->u.Res.f0 = a0_8;
                                            c_78->u.Res.f1 = st0_8;
                                            r_77 = c_78;
                                            break;
                                          }
                                          case 0: {
                                            int64_t a6_5 = x1_29->u.Thunk.f0;
                                            struct Env *x6_3 = x1_29->u.Thunk.f1;
                                            struct Res *x1_30 = x_3(a6_5, x6_3, st0_8);
                                            struct Res *r_79;
                                            switch (x1_30->tag) {
                                            case 0: {
                                              struct Val *a4_8 = x1_30->u.Res.f0;
                                              struct St *a5_5 = x1_30->u.Res.f1;
                                              struct Res *r_80;
                                              switch (a5_5->tag) {
                                              case 0: {
                                                int64_t a0_9 = a5_5->u.St.f0;
                                                struct Heap *a1_7 = a5_5->u.St.f1;
                                                int64_t a2_6 = a5_5->u.St.f2;
                                                struct Cell *c_81 = malloc(sizeof(struct Cell));
                                                c_81->tag = 1;
                                                c_81->u.Done.f0 = a4_8;
                                                struct St *c_82 = malloc(sizeof(struct St));
                                                c_82->tag = 0;
                                                c_82->u.St.f0 = a0_9;
                                                c_82->u.St.f1 = x_1(a1_7, a_5, c_81);
                                                c_82->u.St.f2 = a2_6;
                                                struct Res *c_83 = malloc(sizeof(struct Res));
                                                c_83->tag = 0;
                                                c_83->u.Res.f0 = a4_8;
                                                c_83->u.Res.f1 = c_82;
                                                r_80 = c_83;
                                                break;
                                              }
                                              default:
                                                abort();
                                              }
                                              r_79 = r_80;
                                              break;
                                            }
                                            default:
                                              abort();
                                            }
                                            r_77 = r_79;
                                            break;
                                          }
                                          default:
                                            abort();
                                          }
                                          r_75 = r_77;
                                          break;
                                        }
                                        default:
                                          abort();
                                        }
                                        struct Res *x1_32 = r_75;
                                        struct Res *r_84;
                                        switch (x1_32->tag) {
                                        case 0: {
                                          struct Val *a6_6 = x1_32->u.Res.f0;
                                          struct St *a7 = x1_32->u.Res.f1;
                                          struct Res *r_85;
                                          switch (a6_6->tag) {
                                          case 1: {
                                            struct Env *a2_7 = a6_6->u.VClo.f0;
                                            int64_t a3_14 = a6_6->u.VClo.f1;
                                            struct Res *r_86;
                                            switch (a7->tag) {
                                            case 0: {
                                              int64_t a0_10 = a7->u.St.f0;
                                              struct Heap *a1_8 = a7->u.St.f1;
                                              int64_t a4_9 = a7->u.St.f2;
                                              struct Env *c_87 = malloc(sizeof(struct Env));
                                              c_87->tag = 1;
                                              c_87->u.Bind.f0 = a0_10;
                                              c_87->u.Bind.f1 = a2_7;
                                              struct Cell *c_88 = malloc(sizeof(struct Cell));
                                              c_88->tag = 0;
                                              c_88->u.Thunk.f0 = 11;
                                              c_88->u.Thunk.f1 = env_1;
                                              struct St *c_89 = malloc(sizeof(struct St));
                                              c_89->tag = 0;
                                              c_89->u.St.f0 = (a0_10 + 1);
                                              c_89->u.St.f1 = x_1(a1_8, a0_10, c_88);
                                              c_89->u.St.f2 = a4_9;
                                              r_86 = x_3(a3_14, c_87, c_89);
                                              break;
                                            }
                                            default:
                                              abort();
                                            }
                                            r_85 = r_86;
                                            break;
                                          }
                                          default: {
                                            fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
                                            abort();
                                            r_85 = 0;
                                            break;
                                          }
                                          }
                                          r_84 = r_85;
                                          break;
                                        }
                                        default:
                                          abort();
                                        }
                                        r_73 = r_84;
                                        break;
                                      }
                                      default:
                                        abort();
                                      }
                                      struct Res *x1_35 = r_73;
                                      struct Res *r_90;
                                      switch (x1_35->tag) {
                                      case 0: {
                                        struct Val *a1_9 = x1_35->u.Res.f0;
                                        struct St *a3_15 = x1_35->u.Res.f1;
                                        struct Res *r_91;
                                        switch (a1_9->tag) {
                                        case 0: {
                                          int64_t a0_11 = a1_9->u.VInt.f0;
                                          struct Val *c_92 = malloc(sizeof(struct Val));
                                          c_92->tag = 0;
                                          c_92->u.VInt.f0 = (a2_5 * a0_11);
                                          struct Res *c_93 = malloc(sizeof(struct Res));
                                          c_93->tag = 0;
                                          c_93->u.Res.f0 = c_92;
                                          c_93->u.Res.f1 = a3_15;
                                          r_91 = c_93;
                                          break;
                                        }
                                        default: {
                                          fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",133:36");
                                          abort();
                                          r_91 = 0;
                                          break;
                                        }
                                        }
                                        r_90 = r_91;
                                        break;
                                      }
                                      default:
                                        abort();
                                      }
                                      r_72 = r_90;
                                      break;
                                    }
                                    default: {
                                      fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",129:28");
                                      abort();
                                      r_72 = 0;
                                      break;
                                    }
                                    }
                                    r_71 = r_72;
                                    break;
                                  }
                                  default:
                                    abort();
                                  }
                                  r_60 = r_71;
                                  break;
                                }
                                default:
                                  abort();
                                }
                                r_59 = r_60;
                                break;
                              }
                              case 1: {
                                struct Res *r_94;
                                switch (a3_7->tag) {
                                case 0: {
                                  int64_t x3_12 = a3_7->u.St.f0;
                                  struct Heap *x4_12 = a3_7->u.St.f1;
                                  int64_t x5_11 = a3_7->u.St.f2;
                                  struct St *c_95 = malloc(sizeof(struct St));
                                  c_95->tag = 0;
                                  c_95->u.St.f0 = x3_12;
                                  c_95->u.St.f1 = x4_12;
                                  c_95->u.St.f2 = (x5_11 + 1);
                                  struct St *st0_9 = c_95;
                                  struct Val *c_96 = malloc(sizeof(struct Val));
                                  c_96->tag = 0;
                                  c_96->u.VInt.f0 = 1;
                                  struct Res *c_97 = malloc(sizeof(struct Res));
                                  c_97->tag = 0;
                                  c_97->u.Res.f0 = c_96;
                                  c_97->u.Res.f1 = st0_9;
                                  r_94 = c_97;
                                  break;
                                }
                                default:
                                  abort();
                                }
                                r_59 = r_94;
                                break;
                              }
                              default:
                                abort();
                              }
                              r_58 = r_59;
                              break;
                            }
                            default: {
                              fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",138:28");
                              abort();
                              r_58 = 0;
                              break;
                            }
                            }
                            r_57 = r_58;
                            break;
                          }
                          default:
                            abort();
                          }
                          r_46 = r_57;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_24 = r_46;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_23 = r_24;
                      break;
                    }
                    case 1: {
                      struct Res *r_98;
                      switch (st->tag) {
                      case 0: {
                        int64_t x3_13 = st->u.St.f0;
                        struct Heap *x4_13 = st->u.St.f1;
                        int64_t x5_12 = st->u.St.f2;
                        struct St *c_99 = malloc(sizeof(struct St));
                        c_99->tag = 0;
                        c_99->u.St.f0 = x3_13;
                        c_99->u.St.f1 = x4_13;
                        c_99->u.St.f2 = (x5_12 + 1);
                        struct St *st0_10 = c_99;
                        struct Val *c_100 = malloc(sizeof(struct Val));
                        c_100->tag = 1;
                        c_100->u.VClo.f0 = env_1;
                        c_100->u.VClo.f1 = 10;
                        struct Res *c_101 = malloc(sizeof(struct Res));
                        c_101->tag = 0;
                        c_101->u.Res.f0 = c_100;
                        c_101->u.Res.f1 = st0_10;
                        r_98 = c_101;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_23 = r_98;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_22 = r_23;
                    break;
                  }
                  case 1: {
                    struct Res *r_102;
                    switch (st->tag) {
                    case 0: {
                      int64_t x3_14 = st->u.St.f0;
                      struct Heap *x4_14 = st->u.St.f1;
                      int64_t x5_13 = st->u.St.f2;
                      struct St *c_103 = malloc(sizeof(struct St));
                      c_103->tag = 0;
                      c_103->u.St.f0 = x3_14;
                      c_103->u.St.f1 = x4_14;
                      c_103->u.St.f2 = (x5_13 + 1);
                      struct St *st0_11 = c_103;
                      struct Val *c_104 = malloc(sizeof(struct Val));
                      c_104->tag = 1;
                      c_104->u.VClo.f0 = env_1;
                      c_104->u.VClo.f1 = 9;
                      struct Res *c_105 = malloc(sizeof(struct Res));
                      c_105->tag = 0;
                      c_105->u.Res.f0 = c_104;
                      c_105->u.Res.f1 = st0_11;
                      r_102 = c_105;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_22 = r_102;
                    break;
                  }
                  default:
                    abort();
                  }
                  r_21 = r_22;
                  break;
                }
                case 1: {
                  struct Res *r_106;
                  switch (st->tag) {
                  case 0: {
                    int64_t x3_15 = st->u.St.f0;
                    struct Heap *x4_15 = st->u.St.f1;
                    int64_t x5_14 = st->u.St.f2;
                    struct St *c_107 = malloc(sizeof(struct St));
                    c_107->tag = 0;
                    c_107->u.St.f0 = x3_15;
                    c_107->u.St.f1 = x4_15;
                    c_107->u.St.f2 = (x5_14 + 1);
                    struct St *st0_12 = c_107;
                    int64_t a_6 = x_2(env_1, 0);
                    struct Cell *x1_41 = x(x4_15, a_6);
                    struct Res *r_108;
                    switch (x1_41->tag) {
                    case 1: {
                      struct Val *a0_12 = x1_41->u.Done.f0;
                      struct Res *c_109 = malloc(sizeof(struct Res));
                      c_109->tag = 0;
                      c_109->u.Res.f0 = a0_12;
                      c_109->u.Res.f1 = st0_12;
                      r_108 = c_109;
                      break;
                    }
                    case 0: {
                      int64_t a6_7 = x1_41->u.Thunk.f0;
                      struct Env *x6_4 = x1_41->u.Thunk.f1;
                      struct Res *x1_42 = x_3(a6_7, x6_4, st0_12);
                      struct Res *r_110;
                      switch (x1_42->tag) {
                      case 0: {
                        struct Val *a4_11 = x1_42->u.Res.f0;
                        struct St *a5_9 = x1_42->u.Res.f1;
                        struct Res *r_111;
                        switch (a5_9->tag) {
                        case 0: {
                          int64_t a0_13 = a5_9->u.St.f0;
                          struct Heap *a1_11 = a5_9->u.St.f1;
                          int64_t a2_8 = a5_9->u.St.f2;
                          struct Cell *c_112 = malloc(sizeof(struct Cell));
                          c_112->tag = 1;
                          c_112->u.Done.f0 = a4_11;
                          struct St *c_113 = malloc(sizeof(struct St));
                          c_113->tag = 0;
                          c_113->u.St.f0 = a0_13;
                          c_113->u.St.f1 = x_1(a1_11, a_6, c_112);
                          c_113->u.St.f2 = a2_8;
                          struct Res *c_114 = malloc(sizeof(struct Res));
                          c_114->tag = 0;
                          c_114->u.Res.f0 = a4_11;
                          c_114->u.Res.f1 = c_113;
                          r_111 = c_114;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_110 = r_111;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_108 = r_110;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_106 = r_108;
                    break;
                  }
                  default:
                    abort();
                  }
                  r_21 = r_106;
                  break;
                }
                default:
                  abort();
                }
                r_20 = r_21;
                break;
              }
              case 1: {
                struct Res *r_115;
                switch (st->tag) {
                case 0: {
                  int64_t x3_16 = st->u.St.f0;
                  struct Heap *x4_16 = st->u.St.f1;
                  int64_t x5_15 = st->u.St.f2;
                  struct St *c_116 = malloc(sizeof(struct St));
                  c_116->tag = 0;
                  c_116->u.St.f0 = x3_16;
                  c_116->u.St.f1 = x4_16;
                  c_116->u.St.f2 = (x5_15 + 1);
                  struct St *st0_13 = c_116;
                  struct Res *r_117;
                  switch (st0_13->tag) {
                  case 0: {
                    int64_t x3_17 = st0_13->u.St.f0;
                    struct Heap *x4_17 = st0_13->u.St.f1;
                    int64_t x5_16 = st0_13->u.St.f2;
                    struct St *c_118 = malloc(sizeof(struct St));
                    c_118->tag = 0;
                    c_118->u.St.f0 = x3_17;
                    c_118->u.St.f1 = x4_17;
                    c_118->u.St.f2 = (x5_16 + 1);
                    struct St *st0_14 = c_118;
                    int64_t a_7 = x_2(env_1, 0);
                    struct Cell *x1_46 = x(x4_17, a_7);
                    struct Res *r_119;
                    switch (x1_46->tag) {
                    case 1: {
                      struct Val *a0_14 = x1_46->u.Done.f0;
                      struct Res *c_120 = malloc(sizeof(struct Res));
                      c_120->tag = 0;
                      c_120->u.Res.f0 = a0_14;
                      c_120->u.Res.f1 = st0_14;
                      r_119 = c_120;
                      break;
                    }
                    case 0: {
                      int64_t a6_8 = x1_46->u.Thunk.f0;
                      struct Env *x6_5 = x1_46->u.Thunk.f1;
                      struct Res *x1_47 = x_3(a6_8, x6_5, st0_14);
                      struct Res *r_121;
                      switch (x1_47->tag) {
                      case 0: {
                        struct Val *a4_12 = x1_47->u.Res.f0;
                        struct St *a5_10 = x1_47->u.Res.f1;
                        struct Res *r_122;
                        switch (a5_10->tag) {
                        case 0: {
                          int64_t a0_15 = a5_10->u.St.f0;
                          struct Heap *a1_12 = a5_10->u.St.f1;
                          int64_t a2_9 = a5_10->u.St.f2;
                          struct Cell *c_123 = malloc(sizeof(struct Cell));
                          c_123->tag = 1;
                          c_123->u.Done.f0 = a4_12;
                          struct St *c_124 = malloc(sizeof(struct St));
                          c_124->tag = 0;
                          c_124->u.St.f0 = a0_15;
                          c_124->u.St.f1 = x_1(a1_12, a_7, c_123);
                          c_124->u.St.f2 = a2_9;
                          struct Res *c_125 = malloc(sizeof(struct Res));
                          c_125->tag = 0;
                          c_125->u.Res.f0 = a4_12;
                          c_125->u.Res.f1 = c_124;
                          r_122 = c_125;
                          break;
                        }
                        default:
                          abort();
                        }
                        r_121 = r_122;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_119 = r_121;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_117 = r_119;
                    break;
                  }
                  default:
                    abort();
                  }
                  struct Res *x1_49 = r_117;
                  struct Res *r_126;
                  switch (x1_49->tag) {
                  case 0: {
                    struct Val *a6_9 = x1_49->u.Res.f0;
                    struct St *a7_1 = x1_49->u.Res.f1;
                    struct Res *r_127;
                    switch (a6_9->tag) {
                    case 1: {
                      struct Env *a2_10 = a6_9->u.VClo.f0;
                      int64_t a3_22 = a6_9->u.VClo.f1;
                      struct Res *r_128;
                      switch (a7_1->tag) {
                      case 0: {
                        int64_t a0_16 = a7_1->u.St.f0;
                        struct Heap *a1_13 = a7_1->u.St.f1;
                        int64_t a4_13 = a7_1->u.St.f2;
                        struct Env *c_129 = malloc(sizeof(struct Env));
                        c_129->tag = 1;
                        c_129->u.Bind.f0 = a0_16;
                        c_129->u.Bind.f1 = a2_10;
                        struct Cell *c_130 = malloc(sizeof(struct Cell));
                        c_130->tag = 0;
                        c_130->u.Thunk.f0 = 7;
                        c_130->u.Thunk.f1 = env_1;
                        struct St *c_131 = malloc(sizeof(struct St));
                        c_131->tag = 0;
                        c_131->u.St.f0 = (a0_16 + 1);
                        c_131->u.St.f1 = x_1(a1_13, a0_16, c_130);
                        c_131->u.St.f2 = a4_13;
                        r_128 = x_3(a3_22, c_129, c_131);
                        break;
                      }
                      default:
                        abort();
                      }
                      r_127 = r_128;
                      break;
                    }
                    default: {
                      fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
                      abort();
                      r_127 = 0;
                      break;
                    }
                    }
                    r_126 = r_127;
                    break;
                  }
                  default:
                    abort();
                  }
                  r_115 = r_126;
                  break;
                }
                default:
                  abort();
                }
                r_20 = r_115;
                break;
              }
              default:
                abort();
              }
              r_19 = r_20;
              break;
            }
            case 1: {
              struct Res *r_132;
              switch (st->tag) {
              case 0: {
                int64_t x3_18 = st->u.St.f0;
                struct Heap *x4_18 = st->u.St.f1;
                int64_t x5_17 = st->u.St.f2;
                struct St *c_133 = malloc(sizeof(struct St));
                c_133->tag = 0;
                c_133->u.St.f0 = x3_18;
                c_133->u.St.f1 = x4_18;
                c_133->u.St.f2 = (x5_17 + 1);
                struct St *st0_15 = c_133;
                struct Res *r_134;
                switch (st0_15->tag) {
                case 0: {
                  int64_t x3_19 = st0_15->u.St.f0;
                  struct Heap *x4_19 = st0_15->u.St.f1;
                  int64_t x5_18 = st0_15->u.St.f2;
                  struct St *c_135 = malloc(sizeof(struct St));
                  c_135->tag = 0;
                  c_135->u.St.f0 = x3_19;
                  c_135->u.St.f1 = x4_19;
                  c_135->u.St.f2 = (x5_18 + 1);
                  struct St *st0_16 = c_135;
                  int64_t a_8 = x_2(env_1, 1);
                  struct Cell *x1_54 = x(x4_19, a_8);
                  struct Res *r_136;
                  switch (x1_54->tag) {
                  case 1: {
                    struct Val *a0_17 = x1_54->u.Done.f0;
                    struct Res *c_137 = malloc(sizeof(struct Res));
                    c_137->tag = 0;
                    c_137->u.Res.f0 = a0_17;
                    c_137->u.Res.f1 = st0_16;
                    r_136 = c_137;
                    break;
                  }
                  case 0: {
                    int64_t a6_10 = x1_54->u.Thunk.f0;
                    struct Env *x6_6 = x1_54->u.Thunk.f1;
                    struct Res *x1_55 = x_3(a6_10, x6_6, st0_16);
                    struct Res *r_138;
                    switch (x1_55->tag) {
                    case 0: {
                      struct Val *a4_14 = x1_55->u.Res.f0;
                      struct St *a5_14 = x1_55->u.Res.f1;
                      struct Res *r_139;
                      switch (a5_14->tag) {
                      case 0: {
                        int64_t a0_18 = a5_14->u.St.f0;
                        struct Heap *a1_14 = a5_14->u.St.f1;
                        int64_t a2_11 = a5_14->u.St.f2;
                        struct Cell *c_140 = malloc(sizeof(struct Cell));
                        c_140->tag = 1;
                        c_140->u.Done.f0 = a4_14;
                        struct St *c_141 = malloc(sizeof(struct St));
                        c_141->tag = 0;
                        c_141->u.St.f0 = a0_18;
                        c_141->u.St.f1 = x_1(a1_14, a_8, c_140);
                        c_141->u.St.f2 = a2_11;
                        struct Res *c_142 = malloc(sizeof(struct Res));
                        c_142->tag = 0;
                        c_142->u.Res.f0 = a4_14;
                        c_142->u.Res.f1 = c_141;
                        r_139 = c_142;
                        break;
                      }
                      default:
                        abort();
                      }
                      r_138 = r_139;
                      break;
                    }
                    default:
                      abort();
                    }
                    r_136 = r_138;
                    break;
                  }
                  default:
                    abort();
                  }
                  r_134 = r_136;
                  break;
                }
                default:
                  abort();
                }
                struct Res *x1_57 = r_134;
                struct Res *r_143;
                switch (x1_57->tag) {
                case 0: {
                  struct Val *a6_11 = x1_57->u.Res.f0;
                  struct St *a7_2 = x1_57->u.Res.f1;
                  struct Res *r_144;
                  switch (a6_11->tag) {
                  case 1: {
                    struct Env *a2_12 = a6_11->u.VClo.f0;
                    int64_t a3_26 = a6_11->u.VClo.f1;
                    struct Res *r_145;
                    switch (a7_2->tag) {
                    case 0: {
                      int64_t a0_19 = a7_2->u.St.f0;
                      struct Heap *a1_15 = a7_2->u.St.f1;
                      int64_t a4_15 = a7_2->u.St.f2;
                      struct Env *c_146 = malloc(sizeof(struct Env));
                      c_146->tag = 1;
                      c_146->u.Bind.f0 = a0_19;
                      c_146->u.Bind.f1 = a2_12;
                      struct Cell *c_147 = malloc(sizeof(struct Cell));
                      c_147->tag = 0;
                      c_147->u.Thunk.f0 = 6;
                      c_147->u.Thunk.f1 = env_1;
                      struct St *c_148 = malloc(sizeof(struct St));
                      c_148->tag = 0;
                      c_148->u.St.f0 = (a0_19 + 1);
                      c_148->u.St.f1 = x_1(a1_15, a0_19, c_147);
                      c_148->u.St.f2 = a4_15;
                      r_145 = x_3(a3_26, c_146, c_148);
                      break;
                    }
                    default:
                      abort();
                    }
                    r_144 = r_145;
                    break;
                  }
                  default: {
                    fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
                    abort();
                    r_144 = 0;
                    break;
                  }
                  }
                  r_143 = r_144;
                  break;
                }
                default:
                  abort();
                }
                r_132 = r_143;
                break;
              }
              default:
                abort();
              }
              r_19 = r_132;
              break;
            }
            default:
              abort();
            }
            r_18 = r_19;
            break;
          }
          case 1: {
            struct Res *r_149;
            switch (st->tag) {
            case 0: {
              int64_t x3_20 = st->u.St.f0;
              struct Heap *x4_20 = st->u.St.f1;
              int64_t x5_19 = st->u.St.f2;
              struct St *c_150 = malloc(sizeof(struct St));
              c_150->tag = 0;
              c_150->u.St.f0 = x3_20;
              c_150->u.St.f1 = x4_20;
              c_150->u.St.f2 = (x5_19 + 1);
              struct St *st0_17 = c_150;
              struct Val *c_151 = malloc(sizeof(struct Val));
              c_151->tag = 1;
              c_151->u.VClo.f0 = env_1;
              c_151->u.VClo.f1 = 5;
              struct Res *c_152 = malloc(sizeof(struct Res));
              c_152->tag = 0;
              c_152->u.Res.f0 = c_151;
              c_152->u.Res.f1 = st0_17;
              r_149 = c_152;
              break;
            }
            default:
              abort();
            }
            r_18 = r_149;
            break;
          }
          default:
            abort();
          }
          r_17 = r_18;
          break;
        }
        case 1: {
          struct Res *r_153;
          switch (st->tag) {
          case 0: {
            int64_t x3_21 = st->u.St.f0;
            struct Heap *x4_21 = st->u.St.f1;
            int64_t x5_20 = st->u.St.f2;
            struct St *c_154 = malloc(sizeof(struct St));
            c_154->tag = 0;
            c_154->u.St.f0 = x3_21;
            c_154->u.St.f1 = x4_21;
            c_154->u.St.f2 = (x5_20 + 1);
            struct St *st0_18 = c_154;
            int64_t a_9 = x_2(env_1, 0);
            struct Cell *x1_62 = x(x4_21, a_9);
            struct Res *r_155;
            switch (x1_62->tag) {
            case 1: {
              struct Val *a0_20 = x1_62->u.Done.f0;
              struct Res *c_156 = malloc(sizeof(struct Res));
              c_156->tag = 0;
              c_156->u.Res.f0 = a0_20;
              c_156->u.Res.f1 = st0_18;
              r_155 = c_156;
              break;
            }
            case 0: {
              int64_t a6_12 = x1_62->u.Thunk.f0;
              struct Env *x6_7 = x1_62->u.Thunk.f1;
              struct Res *x1_63 = x_3(a6_12, x6_7, st0_18);
              struct Res *r_157;
              switch (x1_63->tag) {
              case 0: {
                struct Val *a4_16 = x1_63->u.Res.f0;
                struct St *a5_18 = x1_63->u.Res.f1;
                struct Res *r_158;
                switch (a5_18->tag) {
                case 0: {
                  int64_t a0_21 = a5_18->u.St.f0;
                  struct Heap *a1_16 = a5_18->u.St.f1;
                  int64_t a2_13 = a5_18->u.St.f2;
                  struct Cell *c_159 = malloc(sizeof(struct Cell));
                  c_159->tag = 1;
                  c_159->u.Done.f0 = a4_16;
                  struct St *c_160 = malloc(sizeof(struct St));
                  c_160->tag = 0;
                  c_160->u.St.f0 = a0_21;
                  c_160->u.St.f1 = x_1(a1_16, a_9, c_159);
                  c_160->u.St.f2 = a2_13;
                  struct Res *c_161 = malloc(sizeof(struct Res));
                  c_161->tag = 0;
                  c_161->u.Res.f0 = a4_16;
                  c_161->u.Res.f1 = c_160;
                  r_158 = c_161;
                  break;
                }
                default:
                  abort();
                }
                r_157 = r_158;
                break;
              }
              default:
                abort();
              }
              r_155 = r_157;
              break;
            }
            default:
              abort();
            }
            r_153 = r_155;
            break;
          }
          default:
            abort();
          }
          r_17 = r_153;
          break;
        }
        default:
          abort();
        }
        r_16 = r_17;
        break;
      }
      case 1: {
        struct Res *r_162;
        switch (st->tag) {
        case 0: {
          int64_t x3_22 = st->u.St.f0;
          struct Heap *x4_22 = st->u.St.f1;
          int64_t x5_21 = st->u.St.f2;
          struct St *c_163 = malloc(sizeof(struct St));
          c_163->tag = 0;
          c_163->u.St.f0 = x3_22;
          c_163->u.St.f1 = x4_22;
          c_163->u.St.f2 = (x5_21 + 1);
          struct St *st0_19 = c_163;
          struct Res *r_164;
          switch (st0_19->tag) {
          case 0: {
            int64_t x3_23 = st0_19->u.St.f0;
            struct Heap *x4_23 = st0_19->u.St.f1;
            int64_t x5_22 = st0_19->u.St.f2;
            struct St *c_165 = malloc(sizeof(struct St));
            c_165->tag = 0;
            c_165->u.St.f0 = x3_23;
            c_165->u.St.f1 = x4_23;
            c_165->u.St.f2 = (x5_22 + 1);
            struct St *st0_20 = c_165;
            int64_t a_10 = x_2(env_1, 0);
            struct Cell *x1_67 = x(x4_23, a_10);
            struct Res *r_166;
            switch (x1_67->tag) {
            case 1: {
              struct Val *a0_22 = x1_67->u.Done.f0;
              struct Res *c_167 = malloc(sizeof(struct Res));
              c_167->tag = 0;
              c_167->u.Res.f0 = a0_22;
              c_167->u.Res.f1 = st0_20;
              r_166 = c_167;
              break;
            }
            case 0: {
              int64_t a6_13 = x1_67->u.Thunk.f0;
              struct Env *x6_8 = x1_67->u.Thunk.f1;
              struct Res *x1_68 = x_3(a6_13, x6_8, st0_20);
              struct Res *r_168;
              switch (x1_68->tag) {
              case 0: {
                struct Val *a4_17 = x1_68->u.Res.f0;
                struct St *a5_19 = x1_68->u.Res.f1;
                struct Res *r_169;
                switch (a5_19->tag) {
                case 0: {
                  int64_t a0_23 = a5_19->u.St.f0;
                  struct Heap *a1_17 = a5_19->u.St.f1;
                  int64_t a2_14 = a5_19->u.St.f2;
                  struct Cell *c_170 = malloc(sizeof(struct Cell));
                  c_170->tag = 1;
                  c_170->u.Done.f0 = a4_17;
                  struct St *c_171 = malloc(sizeof(struct St));
                  c_171->tag = 0;
                  c_171->u.St.f0 = a0_23;
                  c_171->u.St.f1 = x_1(a1_17, a_10, c_170);
                  c_171->u.St.f2 = a2_14;
                  struct Res *c_172 = malloc(sizeof(struct Res));
                  c_172->tag = 0;
                  c_172->u.Res.f0 = a4_17;
                  c_172->u.Res.f1 = c_171;
                  r_169 = c_172;
                  break;
                }
                default:
                  abort();
                }
                r_168 = r_169;
                break;
              }
              default:
                abort();
              }
              r_166 = r_168;
              break;
            }
            default:
              abort();
            }
            r_164 = r_166;
            break;
          }
          default:
            abort();
          }
          struct Res *x1_70 = r_164;
          struct Res *r_173;
          switch (x1_70->tag) {
          case 0: {
            struct Val *a6_14 = x1_70->u.Res.f0;
            struct St *a7_3 = x1_70->u.Res.f1;
            struct Res *r_174;
            switch (a6_14->tag) {
            case 1: {
              struct Env *a2_15 = a6_14->u.VClo.f0;
              int64_t a3_33 = a6_14->u.VClo.f1;
              struct Res *r_175;
              switch (a7_3->tag) {
              case 0: {
                int64_t a0_24 = a7_3->u.St.f0;
                struct Heap *a1_18 = a7_3->u.St.f1;
                int64_t a4_18 = a7_3->u.St.f2;
                struct Env *c_176 = malloc(sizeof(struct Env));
                c_176->tag = 1;
                c_176->u.Bind.f0 = a0_24;
                c_176->u.Bind.f1 = a2_15;
                struct Cell *c_177 = malloc(sizeof(struct Cell));
                c_177->tag = 0;
                c_177->u.Thunk.f0 = 3;
                c_177->u.Thunk.f1 = env_1;
                struct St *c_178 = malloc(sizeof(struct St));
                c_178->tag = 0;
                c_178->u.St.f0 = (a0_24 + 1);
                c_178->u.St.f1 = x_1(a1_18, a0_24, c_177);
                c_178->u.St.f2 = a4_18;
                r_175 = x_3(a3_33, c_176, c_178);
                break;
              }
              default:
                abort();
              }
              r_174 = r_175;
              break;
            }
            default: {
              fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
              abort();
              r_174 = 0;
              break;
            }
            }
            r_173 = r_174;
            break;
          }
          default:
            abort();
          }
          r_162 = r_173;
          break;
        }
        default:
          abort();
        }
        r_16 = r_162;
        break;
      }
      default:
        abort();
      }
      r_15 = r_16;
      break;
    }
    case 1: {
      struct Res *r_179;
      switch (st->tag) {
      case 0: {
        int64_t x3_24 = st->u.St.f0;
        struct Heap *x4_24 = st->u.St.f1;
        int64_t x5_23 = st->u.St.f2;
        struct St *c_180 = malloc(sizeof(struct St));
        c_180->tag = 0;
        c_180->u.St.f0 = x3_24;
        c_180->u.St.f1 = x4_24;
        c_180->u.St.f2 = (x5_23 + 1);
        struct St *st0_21 = c_180;
        struct Res *r_181;
        switch (st0_21->tag) {
        case 0: {
          int64_t x3_25 = st0_21->u.St.f0;
          struct Heap *x4_25 = st0_21->u.St.f1;
          int64_t x5_24 = st0_21->u.St.f2;
          struct St *c_182 = malloc(sizeof(struct St));
          c_182->tag = 0;
          c_182->u.St.f0 = x3_25;
          c_182->u.St.f1 = x4_25;
          c_182->u.St.f2 = (x5_24 + 1);
          struct St *st0_22 = c_182;
          int64_t a_11 = x_2(env_1, 1);
          struct Cell *x1_75 = x(x4_25, a_11);
          struct Res *r_183;
          switch (x1_75->tag) {
          case 1: {
            struct Val *a0_25 = x1_75->u.Done.f0;
            struct Res *c_184 = malloc(sizeof(struct Res));
            c_184->tag = 0;
            c_184->u.Res.f0 = a0_25;
            c_184->u.Res.f1 = st0_22;
            r_183 = c_184;
            break;
          }
          case 0: {
            int64_t a6_15 = x1_75->u.Thunk.f0;
            struct Env *x6_9 = x1_75->u.Thunk.f1;
            struct Res *x1_76 = x_3(a6_15, x6_9, st0_22);
            struct Res *r_185;
            switch (x1_76->tag) {
            case 0: {
              struct Val *a4_19 = x1_76->u.Res.f0;
              struct St *a5_23 = x1_76->u.Res.f1;
              struct Res *r_186;
              switch (a5_23->tag) {
              case 0: {
                int64_t a0_26 = a5_23->u.St.f0;
                struct Heap *a1_19 = a5_23->u.St.f1;
                int64_t a2_16 = a5_23->u.St.f2;
                struct Cell *c_187 = malloc(sizeof(struct Cell));
                c_187->tag = 1;
                c_187->u.Done.f0 = a4_19;
                struct St *c_188 = malloc(sizeof(struct St));
                c_188->tag = 0;
                c_188->u.St.f0 = a0_26;
                c_188->u.St.f1 = x_1(a1_19, a_11, c_187);
                c_188->u.St.f2 = a2_16;
                struct Res *c_189 = malloc(sizeof(struct Res));
                c_189->tag = 0;
                c_189->u.Res.f0 = a4_19;
                c_189->u.Res.f1 = c_188;
                r_186 = c_189;
                break;
              }
              default:
                abort();
              }
              r_185 = r_186;
              break;
            }
            default:
              abort();
            }
            r_183 = r_185;
            break;
          }
          default:
            abort();
          }
          r_181 = r_183;
          break;
        }
        default:
          abort();
        }
        struct Res *x1_78 = r_181;
        struct Res *r_190;
        switch (x1_78->tag) {
        case 0: {
          struct Val *a6_16 = x1_78->u.Res.f0;
          struct St *a7_4 = x1_78->u.Res.f1;
          struct Res *r_191;
          switch (a6_16->tag) {
          case 1: {
            struct Env *a2_17 = a6_16->u.VClo.f0;
            int64_t a3_37 = a6_16->u.VClo.f1;
            struct Res *r_192;
            switch (a7_4->tag) {
            case 0: {
              int64_t a0_27 = a7_4->u.St.f0;
              struct Heap *a1_20 = a7_4->u.St.f1;
              int64_t a4_20 = a7_4->u.St.f2;
              struct Env *c_193 = malloc(sizeof(struct Env));
              c_193->tag = 1;
              c_193->u.Bind.f0 = a0_27;
              c_193->u.Bind.f1 = a2_17;
              struct Cell *c_194 = malloc(sizeof(struct Cell));
              c_194->tag = 0;
              c_194->u.Thunk.f0 = 2;
              c_194->u.Thunk.f1 = env_1;
              struct St *c_195 = malloc(sizeof(struct St));
              c_195->tag = 0;
              c_195->u.St.f0 = (a0_27 + 1);
              c_195->u.St.f1 = x_1(a1_20, a0_27, c_194);
              c_195->u.St.f2 = a4_20;
              r_192 = x_3(a3_37, c_193, c_195);
              break;
            }
            default:
              abort();
            }
            r_191 = r_192;
            break;
          }
          default: {
            fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
            abort();
            r_191 = 0;
            break;
          }
          }
          r_190 = r_191;
          break;
        }
        default:
          abort();
        }
        r_179 = r_190;
        break;
      }
      default:
        abort();
      }
      r_15 = r_179;
      break;
    }
    default:
      abort();
    }
    r_14 = r_15;
    break;
  }
  case 1: {
    struct Res *r_196;
    switch (st->tag) {
    case 0: {
      int64_t x3_26 = st->u.St.f0;
      struct Heap *x4_26 = st->u.St.f1;
      int64_t x5_25 = st->u.St.f2;
      struct St *c_197 = malloc(sizeof(struct St));
      c_197->tag = 0;
      c_197->u.St.f0 = x3_26;
      c_197->u.St.f1 = x4_26;
      c_197->u.St.f2 = (x5_25 + 1);
      struct St *st0_23 = c_197;
      struct Res *r_198;
      switch (st0_23->tag) {
      case 0: {
        int64_t x3_27 = st0_23->u.St.f0;
        struct Heap *x4_27 = st0_23->u.St.f1;
        int64_t x5_26 = st0_23->u.St.f2;
        struct St *c_199 = malloc(sizeof(struct St));
        c_199->tag = 0;
        c_199->u.St.f0 = x3_27;
        c_199->u.St.f1 = x4_27;
        c_199->u.St.f2 = (x5_26 + 1);
        struct St *st0_24 = c_199;
        struct Val *c_200 = malloc(sizeof(struct Val));
        c_200->tag = 1;
        c_200->u.VClo.f0 = env_1;
        c_200->u.VClo.f1 = 1;
        struct Res *c_201 = malloc(sizeof(struct Res));
        c_201->tag = 0;
        c_201->u.Res.f0 = c_200;
        c_201->u.Res.f1 = st0_24;
        r_198 = c_201;
        break;
      }
      default:
        abort();
      }
      struct Res *x1_83 = r_198;
      struct Res *r_202;
      switch (x1_83->tag) {
      case 0: {
        struct Val *a6_17 = x1_83->u.Res.f0;
        struct St *a7_5 = x1_83->u.Res.f1;
        struct Res *r_203;
        switch (a6_17->tag) {
        case 1: {
          struct Env *a2_18 = a6_17->u.VClo.f0;
          int64_t a3_38 = a6_17->u.VClo.f1;
          struct Res *r_204;
          switch (a7_5->tag) {
          case 0: {
            int64_t a0_28 = a7_5->u.St.f0;
            struct Heap *a1_21 = a7_5->u.St.f1;
            int64_t a4_21 = a7_5->u.St.f2;
            struct Env *c_205 = malloc(sizeof(struct Env));
            c_205->tag = 1;
            c_205->u.Bind.f0 = a0_28;
            c_205->u.Bind.f1 = a2_18;
            struct Cell *c_206 = malloc(sizeof(struct Cell));
            c_206->tag = 0;
            c_206->u.Thunk.f0 = 4;
            c_206->u.Thunk.f1 = env_1;
            struct St *c_207 = malloc(sizeof(struct St));
            c_207->tag = 0;
            c_207->u.St.f0 = (a0_28 + 1);
            c_207->u.St.f1 = x_1(a1_21, a0_28, c_206);
            c_207->u.St.f2 = a4_21;
            r_204 = x_3(a3_38, c_205, c_207);
            break;
          }
          default:
            abort();
          }
          r_203 = r_204;
          break;
        }
        default: {
          fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
          abort();
          r_203 = 0;
          break;
        }
        }
        r_202 = r_203;
        break;
      }
      default:
        abort();
      }
      r_196 = r_202;
      break;
    }
    default:
      abort();
    }
    r_14 = r_196;
    break;
  }
  default:
    abort();
  }
  return r_14;
}

struct Res *pfactorial() {
  struct Heap *c_208 = malloc(sizeof(struct Heap));
  c_208->tag = 0;
  struct St *c_209 = malloc(sizeof(struct St));
  c_209->tag = 0;
  c_209->u.St.f0 = 1;
  c_209->u.St.f1 = c_208;
  c_209->u.St.f2 = 0;
  struct St *x1_86 = c_209;
  struct Res *r_210;
  switch (x1_86->tag) {
  case 0: {
    int64_t x3_28 = x1_86->u.St.f0;
    struct Heap *x4_28 = x1_86->u.St.f1;
    int64_t x5_27 = x1_86->u.St.f2;
    struct St *c_211 = malloc(sizeof(struct St));
    c_211->tag = 0;
    c_211->u.St.f0 = x3_28;
    c_211->u.St.f1 = x4_28;
    c_211->u.St.f2 = (x5_27 + 1);
    struct St *st0_25 = c_211;
    struct Res *r_212;
    switch (st0_25->tag) {
    case 0: {
      int64_t x3_29 = st0_25->u.St.f0;
      struct Heap *x4_29 = st0_25->u.St.f1;
      int64_t x5_28 = st0_25->u.St.f2;
      struct St *c_213 = malloc(sizeof(struct St));
      c_213->tag = 0;
      c_213->u.St.f0 = x3_29;
      c_213->u.St.f1 = x4_29;
      c_213->u.St.f2 = (x5_28 + 1);
      struct St *st0_26 = c_213;
      struct Env *c_214 = malloc(sizeof(struct Env));
      c_214->tag = 0;
      struct Val *c_215 = malloc(sizeof(struct Val));
      c_215->tag = 1;
      c_215->u.VClo.f0 = c_214;
      c_215->u.VClo.f1 = 0;
      struct Res *c_216 = malloc(sizeof(struct Res));
      c_216->tag = 0;
      c_216->u.Res.f0 = c_215;
      c_216->u.Res.f1 = st0_26;
      r_212 = c_216;
      break;
    }
    default:
      abort();
    }
    struct Res *x1_88 = r_212;
    struct Res *r_217;
    switch (x1_88->tag) {
    case 0: {
      struct Val *a6_18 = x1_88->u.Res.f0;
      struct St *a7_6 = x1_88->u.Res.f1;
      struct Res *r_218;
      switch (a6_18->tag) {
      case 1: {
        struct Env *a2_19 = a6_18->u.VClo.f0;
        int64_t a3_39 = a6_18->u.VClo.f1;
        struct Res *r_219;
        switch (a7_6->tag) {
        case 0: {
          int64_t a0_29 = a7_6->u.St.f0;
          struct Heap *a1_22 = a7_6->u.St.f1;
          int64_t a4_22 = a7_6->u.St.f2;
          struct Env *c_220 = malloc(sizeof(struct Env));
          c_220->tag = 1;
          c_220->u.Bind.f0 = a0_29;
          c_220->u.Bind.f1 = a2_19;
          struct Env *c_221 = malloc(sizeof(struct Env));
          c_221->tag = 0;
          struct Cell *c_222 = malloc(sizeof(struct Cell));
          c_222->tag = 0;
          c_222->u.Thunk.f0 = 8;
          c_222->u.Thunk.f1 = c_221;
          struct St *c_223 = malloc(sizeof(struct St));
          c_223->tag = 0;
          c_223->u.St.f0 = (a0_29 + 1);
          c_223->u.St.f1 = x_1(a1_22, a0_29, c_222);
          c_223->u.St.f2 = a4_22;
          r_219 = x_3(a3_39, c_220, c_223);
          break;
        }
        default:
          abort();
        }
        r_218 = r_219;
        break;
      }
      default: {
        fprintf(stderr, "%s\n", "\"./LowFutamura.hs\",119:28");
        abort();
        r_218 = 0;
        break;
      }
      }
      r_217 = r_218;
      break;
    }
    default:
      abort();
    }
    r_210 = r_217;
    break;
  }
  default:
    abort();
  }
  return r_210;
}
